### ISSUE TITLE
Issue with data storage and re-animated (mobx-state-tree)

### ISSUE THREAD

**Issue by owattenmaker** [FormidableLabs/victory-native-xl#114]
Hello.

Not sure this is an issue with your code, but perhaps you could offer some guidance on how you usually store data to pass to these components.

I'm building a tide app and we have thousands of datapoints coming from our API. The way I currently structured it is all of the data gets stored in mobx, then the UI component simply has to display it.

This worked well with victory-native, and there didn't seem to be any issue with this approach. I like the new API you've built. I think it's much simpler than the old API and would like to use it going forward.

However when I am testing out your library, I get an error coming from reanimated showing the following:
```
ReanimatedError: [Reanimated] Trying to access property `__remoteFunction` of an object which cannot be sent to the UI runtime., js engine: reanimated
```

<img src="https://github.com/FormidableLabs/victory-native-xl/assets/10779381/357aed76-d628-41da-a9d1-8f5b2f42395e" width="200" />

Curiously the chart renders properly for one frame before showing this error. I believe this is caused by the data being lazy loaded from mobx

I have two questions.
1. Have you used things like mobx to store data before?
2. What libraries/solutions would you suggest for data storage to be able to pass over the UI bridge?

**Comment by owattenmaker** [comment]
And please feel free to close this issue if you think it's the wrong scope for the library. I am just posting this here in case any others testing out the library happen to run into a similar issue

**Comment by keithluchtel** [comment]
@owattenmaker can you provide a minimal example of how you're trying to pull data from MST and display the data in a chart?

**Comment by owattenmaker** [comment]
OKAY!

 I figured it out. if you pass in a js `Date` object for the xKey then it breaks.
I got around this by passing in the epoch time.

Thanks for taking the time to respond. Hopefully this thread can help anyone else experiencing the same problem
