### ISSUE TITLE
satisfies operator prevents building in javascript project

### ISSUE THREAD

**Issue by tomasmozeris** [FormidableLabs/victory-native-xl#140]
### Question

Having issue in **javascript** project with **satisfies** typescript operator.
https://github.com/search?q=repo%3AFormidableLabs%2Fvictory-native-xl%20satisfies&type=code
Maybe it is possible to replace that operator with another to keep library working for javascript based projects?

### Background Iinfo/Attempts

Tried updating "@babel/core" and "metro-react-native-babel-preset" without any luck.
So I patched by removing these types from defaultProps and projects builds successfully.

Thanks for this library, examples performance looks great

**Comment by gksander** [comment]
I'll look into this! This might be a simple configuration issue in our package.json file. Sounds like maybe your project is trying to consume the typescript source files from this library, which I think is a small issue on the library side.

**Comment by HaydenPWoods** [comment]
In case it is useful - I had the same (or similar?) issue yesterday getting victory-native working in an existing project, whilst it ran fine on a fresh new one. It would fail to bundle the JavaScript with the below error (unexpected "satisfies"):

```
error node_modules\victory-native\src\cartesian\components\Bar.tsx: Unexpected token name «satisfies», expected punc «,» in file node_modules\victory-native\src\cartesian\components\Bar.tsx at 31:4.
Error: Unexpected token name «satisfies», expected punc «,» in file node_modules\victory-native\src\cartesian\components\Bar.tsx at 31:4
    at minifyCode (D:\birdtrack\node_modules\metro-transform-worker\src\index.js:88:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async transformJS (D:\birdtrack\node_modules\metro-transform-worker\src\index.js:275:22)
    at async transformJSWithBabel (D:\birdtrack\node_modules\metro-transform-worker\src\index.js:343:10)
    at async Object.transform (D:\birdtrack\node_modules\metro-transform-worker\src\index.js:461:12)
```

Deleting yarn.lock and the whole node_modules folder, and running yarn again seemed to solve it for me.

https://github.com/facebook/metro/issues/1065#issuecomment-1695346819 suggests it was an old Babel package hanging about.

**Comment by zibs** [comment]
Hey @tomasmozeris -- if you can provide some more info I can take a look at this. I am able to run a JS-only Expo project with a bar chart at the moment.

The Issues template has a bunch of info that would be useful if you can provide, thanks! (Or better yet, a Snack that can reproduce, thanks!)

**Comment by tomasmozeris** [comment]
> Hey @tomasmozeris -- if you can provide some more info I can take a look at this. I am able to run a JS-only Expo project with a bar chart at the moment.
> 
> The Issues template has a bunch of info that would be useful if you can provide, thanks! (Or better yet, a Snack that can reproduce, thanks!)

Hey, cleaned patch to check if projects builds with current packages and it did, no problem anymore
