### ISSUE TITLE
Pie chart support

### ISSUE THREAD

**Issue by Hanro50** [FormidableLabs/victory-native-xl#141]
### Description
The primary function I use victory for in my react native project is pie-charts. However it seems the ability to create and use pie-charts is absent as per the current support documentation on the website. Pulling Victory 40 into a project that used Victory 36 previously results in errors cropping up due to the changes made in the underlying components. The victory pie component doesn't seem to exist anymore. 

### Proposal
It would be nice if they where added back, perhaps with some additional features that can, for instance, prevent labels from colliding with one another as they do currently and perhaps allow for rounded edges on different segments with donut style pie-charts.

**Comment by maxVelychko** [comment]
Looking forward for the Pie chart support!
Thanks to Formidable Team to make the charts already working on React native!

**Comment by angusryer** [comment]
Agreed. I cannot use `victory-native` v40 because of this.

**Comment by zibs** [comment]
@angusryer It's in progress #191 to track if you're interested

**Comment by zibs** [comment]
#191 landed and was released, so closing this for now as it brought in initial Pie/Donut support.
