### ISSUE TITLE
Not able to plot graph. Getting error undefined is not a function

### ISSUE THREAD

**Issue by pandeyshivam21197** [FormidableLabs/victory-native-xl#146]
### Prerequisites

- [x] I have searched the open [issues](https://www.github.com/FormidableLabs/victory-native-xl/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/victory-native-xl/docs) before asking a question
- [x] I am using the latest version of victory-native-xl

### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`): 40.0.2

**What version of React and React Native are you using?**: 0.69.4

**What version of Reanimated and React Native Skia are you using?**: reanimated: 2.9.1, skia: 0.1.213

**Are you using Expo or React Native CLI?** react native CLI

**What platform are you on?** (e.g., iOS, Android): IOS

### Describe the Problem

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Comment by pandey21197** [comment]
This is because of old hermes engine which does not support at method on Arrays.

Add a your custom method on Array prototype at your index entry file :

Array.prototype.at = function (index) {
  if (index > this.length - 1) {
    return undefined;
  }

  return this[index];
};
