### ISSUE TITLE
How to deal with multiple gesture handlers?

### ISSUE THREAD

**Issue by admapop** [FormidableLabs/victory-native-xl#149]
### Question

How to deal with multiple gesture handlers?

### Background Info/Attempts

I'm building a CartesianChart, and one of the requirements is to be able to swipe on the chart to change the time series window, basically swiping back and forth in time. Now this works very well, however, as soon as I add tooltips to the mix the Gesture Handler Root View that wraps the CartesianChart hijacks all events.

**Comment by zibs** [comment]
We are looking into a way to support passing in your own custom gestures which would probably help unlock this.

**Comment by keithluchtel** [comment]
I know this is old, but recently we've added support for custom gesture handlers and combining multiple gestures. Going to mark closed.
