### ISSUE TITLE
Getting started example does not work

### ISSUE THREAD

**Issue by milkmouth** [FormidableLabs/victory-native-xl#156]
### Prerequisites

- [v] I have searched the open [issues](https://www.github.com/FormidableLabs/victory-native-xl/issues) to make sure I'm not opening a duplicate issue
- [v] I have read through the [docs](https://www.formidable.com/open-source/victory-native-xl/docs) before asking a question
- [v] I am using the latest version of victory-native-xl

### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`) victory-native@40.0.2

**What version of React and React Native are you using?** react 18.2.0 react-native 0.72.6

**What version of Reanimated and React Native Skia are you using?** 0.1.214

**Are you using Expo or React Native CLI?** React Native CLI

**What platform are you on?** (e.g., iOS, Android) IOS and Android

### Describe the Problem

**Expected behavior:** [What you expect to happen]

I tried to get the minimal example working

**Actual behavior:** [What actually happens]

1. yarn add react-native-reanimated react-native-gesture-handler @shopify/react-native-skia
2. For Reanimated, you'll need to add "react-native-reanimated/plugin" to your plugins list in your babel.config.js config file.
3. yarn add victory-native
4. `const DATA = Array.from({ length: 31 }, (_, i) => ({
  day: i,
  highTmp: 40 + 30 * Math.random(),
}));
`
5. `import { CartesianChart } from "victory-native";`
6. `<CartesianChart data={DATA} xKey="day" yKeys={["highTmp"]} />`

7. 

> TypeError: children is not a function (it is undefined) CartesianChart.tsx (367:36)
This error is located at:
    in CartesianChart (created by _c)
    in RCTView (created by View)
    in View (created by _c)
    in _c (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenNavigationContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by _c)
    in _c (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by HomeStackNavigator)
    in HomeStackNavigator
    in RCTSafeAreaView
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider
    in Unknown
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in lcwc(RootComponent), js engine: hermes

**Comment by owattenmaker** [comment]
It's just yelling at you bc you didn't pass any children. Nothing will render if you don't give it anything. If you want to have what you put work, add `children={() => null}` as a prop
