### ISSUE TITLE
MakeAnimatedImageFromEncoded

### ISSUE THREAD

**Issue by Elson-Timana** [FormidableLabs/victory-native-xl#160]
TypeError: Cannot read property 'MakeAnimatedImageFromEncoded' of undefined, js engine: hermes

![image](https://github.com/FormidableLabs/victory-native-xl/assets/8736811/13081b6e-8827-415f-93d5-82b1480da40b)

**Comment by keithluchtel** [comment]
> Are you using Expo? If so you have to create a development build in order for this package to work.

That's not true. The example app with this package is using Expo Go

**Comment by keithluchtel** [comment]
> Are you using Expo? If so you have to create a development build in order for this package to work.

This isn't true, victory-native-xl will work with Expo Go

**Comment by keithluchtel** [comment]
> > > Are you using Expo? If so you have to create a development build in order for this package to work.
> > 
> > 
> > This isn't true, victory-native-xl will work with Expo Go
> 
> Then I'm probably doing something wrong, but following the [Getting started guide](https://formidable.com/open-source/victory-native/getting-started) does not work for me in a fresh Expo project, I get the same error as Elson-Timana here.

If you put together a minimal reproduction repo, I can take a look

**Comment by keithluchtel** [comment]
> > If you put together a minimal reproduction repo, I can take a look
> 
> Thank you. I put together a [repo here](https://github.com/svenngronbeck/with-victory-native).
> 
> Two issues:
> 
>     1. `yarn add victory-native` (as per the guide) adds version @36.5.12, so I manually have to edit this to @40.0.2 in package.json, delete node_modules and run `yarn` again to get the correct version.
> 
>     2. I get the exact same error as described in this issue when I run `yarn ios`

It's an issue with your dependency version. Updating to the following works without the error:

```
  "dependencies": {
    "@shopify/react-native-skia": "0.1.196",
    "@types/react": "~18.2.14",
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",
    "typescript": "^5.1.3",
    "victory-native": "^40.0.2"
  },
```

When using Expo, I recommend adding packages using `npx expo install <package-name>`. This will ensure you're adding the version of the package that is compatible with the version of Expo you're currently using.
