### ISSUE TITLE
Cold start blank view

### ISSUE THREAD

**Issue by omer921** [FormidableLabs/victory-native-xl#161]
We're seeing some minor performance issues when starting from a cold start -- it takes around two seconds for the graph to render while the rest of the components on the screen have already rendered. 

Is there a onLoadStart or onLoadEnd property we can listen to in order to provide a loading screen while the graph is being rendered?

**Comment by zibs** [comment]
Hey @omer921 -- if you're still interested in this can you provide a few more details about what you're seeing?

I'd like to know the type/shape of dataset you're using + the chart components. A simple reproducible example would be best!

Thanks.
