### ISSUE TITLE
Gesture.Pan handler causes entire screen to freeze when onFinalize isn't called

### ISSUE THREAD

**Issue by owattenmaker** [FormidableLabs/victory-native-xl#163]
### The problem:
If you manage to skip the `onFinalize` call when the `Gesture.Pan` is happening, the gesture handler will take over all finger events until you touch the area again and the `onFinalize` gets correctly called.

The only consistent way I've gotten this to happen is if the chart goes under the navigation bar (at least on iOS). The gesture handler starts tracking your touches, but never finishes because you've either gone into the app switcher or to the home screen.

If you console.log the events, you can see the `onFinalize` or `onTouchesUp` is never called, causing the gesture to never "end", and thus block all new gestures from starting when resuming the app. 

### The culprit
Line 195 of `CartesianChart.tsx` contains the following:
```ts
const touchGesture = Gesture.Pan()
    .manualActivation(true)
...
```

The issue I've noticed is specifically with the `manualActivation` part of it. I'm unsure what the intended functionality of this line is. I believe it's some confusion regarding the docs of `react-native-gesture-handler`, specifically [here](https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/manual-gestures/#modifying-existing-gestures). There's a small note about using `.manualActivation(true)` when using `.activateAfterLongPress`. 

I think the docs are poorly worded and just saying `.activateAfterLongPress` is a shorthand for using `.manualActivation`. 

If I remove manual activation from the gesture, the gesture and touch state still works exactly as intended, but the issue of going over the nav bar no longer happens. 

I haven't tested with multiple fingers if the removal of manual activation breaks it.

**Comment by zibs** [comment]
This should be fixed via the latest release of `40.0.4` -- Let me know if this is the case or not!
