### ISSUE TITLE
Android activateAfterLongPress gesture handler

### ISSUE THREAD

**Issue by tomasmozeris** [FormidableLabs/victory-native-xl#165]
### Question

Android doesn't allow to use the ScrollView on CartesianChart

### Background Info/Attempts

- Tried increasing `activateAfterLongPress` value to 2000ms
https://github.com/FormidableLabs/victory-native-xl/blob/c24eabfa92f7a27ded0177ba114620ed5cdcdc0c/lib/src/cartesian/CartesianChart.tsx#L290
- Tried ensuring single `<GestureHandlerRootView /> `
- Tried researching if anybody has similar issues with `activateAfterLongPress` in `react-native-gesture-handler`

**Comment by tomasmozeris** [comment]
If anybody comes with same problem, this patch works pretty well
https://github.com/ottor-o/victory-native-xl/commit/d119cff664c3c00a0c2ec93e0d04db306ea48e00

**Comment by derekpwu** [comment]
We were able to fix this by disabling the `manual activation` and moving `gestureState.value.isGestureActive = true` to onStart on Android. From our findings, it seems like manual activation on Android would break out of the delay that was set from `activateAfterLongPress` and register the touch right away. Moving the setter to `onStart` is that `onBegin` is called as soon as you touch the screen, without waiting for the delay. 
For iOS, we would need to keep the original implementation though. 

Hope these helps

**Comment by zibs** [comment]
This should be fixed via the latest release of `40.0.4`
