### ISSUE TITLE
roundedCorners gets distorted on smaller values 

### ISSUE THREAD

**Issue by lukebars** [FormidableLabs/victory-native-xl#167]
### Prerequisites

- [x] I have searched the open [issues](https://www.github.com/FormidableLabs/victory-native-xl/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/victory-native-xl/docs) before asking a question
- [x] I am using the latest version of `victory-native-xl`

### Describe Your Environment

**What version of victory-native-xl are you using?**
```json
    "victory-native": "40.0.2",
```

**What version of React and React Native are you using?**
```json
    "react": "18.2.0",
    "react-native": "0.72.7",
```

**What version of Reanimated and React Native Skia are you using?**
```json
    "react-native-reanimated": "3.5.4",
    "@shopify/react-native-skia": "^0.1.202",
```

**Are you using Expo or React Native CLI?**
React Native CLI

**What platform are you on?** (e.g., iOS, Android)
iOS

### Describe the Problem

Property `roundedCorners` breaks value representation on smaller values.

```
  <BarGroup
            chartBounds={chartBounds}
            betweenGroupPadding={0.3}
            withinGroupPadding={0}
            roundedCorners={{
              topLeft: 13,
              topRight: 13,
              bottomLeft: 13,
              bottomRight: 13,
            }}
          >
            <BarGroup.Bar
              points={points.milestones}
              color={theme.colors.primary}
            />
          </BarGroup>
```

**Expected behavior:** [What you expect to happen]

Perfectly round corners

**Actual behavior:** [What actually happens]

In my case if value is less than 15 in this case, rounded corners are inverted or distorted:

(this example is rotated 90 degrees, but it happens on non-rotated version too)
<img width="282" alt="image" src="https://github.com/FormidableLabs/victory-native-xl/assets/46403446/bc82bbda-f8d1-47d0-b381-a457146e7969">
(here we're seeing another type of distortion)
<img width="780" alt="image" src="https://github.com/FormidableLabs/victory-native-xl/assets/46403446/48622079-2eaa-4e1d-8fd0-40800efbde0f">

### Additional Information

Example no. 1 should be representing these numbers:

```js
const skillLevels = [
    50
    10,
    23,
    18,
];
```

**Comment by hamadbhassan** [comment]
My current workaround for this is patching the useBarPath

from 
```
      const roundedRectPath = Skia.Path.MakeFromSVGString(
        createRoundedRectPath(
          x - barWidth / 2,
          y,
          barWidth,
          chartBounds.bottom - y,
          roundedCorners,
        ),
      );
```

to

```     const roundedRectPath = Skia.Path.MakeFromSVGString(
        createRoundedRectPath(
          x - barWidth / 2,
          y,
          barWidth,
          chartBounds.bottom - y,
          yValue < roundedCorners.bottomLeft ? {
            bottomLeft: yValue,
            bottomRight: yValue,
            topLeft: yValue,
            topRight: yValue
          } : roundedCorners
        )
      )

**Comment by masiddee** [comment]
> My current workaround for this is patching the useBarPath
> 
> from
> 
> ```
>       const roundedRectPath = Skia.Path.MakeFromSVGString(
>         createRoundedRectPath(
>           x - barWidth / 2,
>           y,
>           barWidth,
>           chartBounds.bottom - y,
>           roundedCorners,
>         ),
>       );
> ```
> 
> to
> 
> ```
>         createRoundedRectPath(
>           x - barWidth / 2,
>           y,
>           barWidth,
>           chartBounds.bottom - y,
>           yValue < roundedCorners.bottomLeft ? {
>             bottomLeft: yValue,
>             bottomRight: yValue,
>             topLeft: yValue,
>             topRight: yValue
>           } : roundedCorners
>         )
>       )
> ```

@lukebars I had a chance to test, and can confirm that this problem only occurs when specifying `bottomLeft` and `bottomRight` rounded corners -- this does not happen when just the 2 top parameters are defined, no matter the value.

With that said, the patch from @hamadbhassan looks to be the best solution here, as it prevents the bars from folding in on themselves, though with a minor side effect in the UI -- namely, the rounded corners will be of varying sizes, depending on the `yValue` of each data point (see my screenshot below):

![Simulator Screen Shot - iPhone 14 Pro Max - 2024-02-16 at 11 25 11](https://github.com/FormidableLabs/victory-native-xl/assets/5460663/cb6324ff-b69e-4c52-9696-3533ace5693e)

Considering this, I'll go ahead and close out this issue. Thanks again!
