### ISSUE TITLE
Minimum & Maximum values in axes?

### ISSUE THREAD

**Issue by AroundTheLines** [FormidableLabs/victory-native-xl#169]
### Question

Is it possible to set a minimum and maximum value that the axes will display within a `CartesianChart`? I have a dataset that has negative values which is needed for formatting a tooltip, but I would like negative values not to be displayed on the graph.

**Comment by zibs** [comment]
Hey @AroundTheLines -- I believe you are looking for the `domain` prop on the `CartesianChart`: https://github.com/FormidableLabs/victory-native-xl/blob/main/lib/src/cartesian/CartesianChart.tsx#L38

You can set the min/max via something like: `domain={{ y: [minY, maxY] }}` etc

I don't think this is actually in the docs though, so thank you for calling it out and I'll add it.
