### ISSUE TITLE
Bar colors

### ISSUE THREAD

**Issue by Willham12** [FormidableLabs/victory-native-xl#170]
How can i change a color of a single bar?

<img width="420" alt="mg" src="https://github.com/FormidableLabs/victory-native-xl/assets/87827270/741798e5-1f46-42c6-a28e-9717c2fb61fb">

**Comment by carloskelly13** [comment]
Hi, each `<Bar />` path takes a singular color applied to the entire set. Eject from the default components and render bars manually if you want more precise control. You can do this with the `points` object. In our examples is a demonstration of how to do custom drawing → https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/custom-drawing.tsx#L59-L78
