### ISSUE TITLE
Points is returning as empty object 

### ISSUE THREAD

**Issue by mervAyz** [FormidableLabs/victory-native-xl#172]
### Prerequisites

- [x] I have searched the open [issues](https://www.github.com/FormidableLabs/victory-native-xl/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/victory-native-xl/docs) before asking a question
- [x] I am using the latest version of victory-native-xl

### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`) ->40.0.2

**What version of React and React Native are you using?**-> React: 18.1.0   React Native: 0.70.6

**What version of Reanimated and React Native Skia are you using?** Reanimated:3.3.0  React Native Skia: 0.1.225

**Are you using Expo or React Native CLI?** React Native CLI

**What platform are you on?** (e.g., iOS, Android) Android

### Problem

I am experiencing an issue with my code where the `points`  is returning empty object when attempting to create a line chart using the library.

**Expected behavior:**  The points not returning empty and the graph being drawn on the screen

**Actual behavior:** The points are returning empty objects and the graph is not drawn.

### Additional Information

```
const DATA = (numberPoints = 13) =>
  Array.from({ length: numberPoints }, (_, index) => ({
    day: index + 1,
    sales: randomNumber(),
  }));

  const dataPoints = DATA(); // Calling the DATA function
console.log(dataPoints); // Logging the result

const App = () => {
  return (
    <View style={{ height: 300 }}>
      <CartesianChart
        data={dataPoints}
        xKey="day"
        yKeys={["highTmp"]}
        // 👇 pass the font, opting in to axes.
        // axisOptions={{ font }}
      >
        {({ points }) => (
          <>
           {console.log("points",points)}
          <Line points={points.highTmp} color="red" strokeWidth={3} />
          </>
        )}
      </CartesianChart>
    </View>

  );
};
```

**Comment by mervAyz** [comment]
I had to upgrade my React and React-Native version to 18.2.0 and 0.71.14. To avoid changing React and React-native version, I added the below code block to my code, but it caused the problem. So I upgraded my React and React-native version to 18.1.0 -> 18.2.0 and 0.70.6 -> 0.71.14

>Array.prototype.at = function (index) {
  if (index > this.length - 1) {
  return undefined;
  }
   return this[index];
  };
  
I also made some fixes in the code above. 

> sales: Math.random(),

> yKeys={["highTmp"]} , points={points.highTmp} to yKeys={["sales"]} , points={points.sales}

**Comment by zibs** [comment]
Just to follow up due to some confusion we're seeing: https://github.com/FormidableLabs/victory-native-xl/issues/312#issuecomment-2237471144

> One aspect of the confusion here is that points is not truly an empty object. It's actually a Proxy and maybe we need to make that more clear in the docs somewhere. You can successfully log its values by using the yKeys of your data. So, if you logged points.spent, you will see the transformed data.

> So my suggestions here is to review the styles applied to the chart/chart container, and log the actual points[yKey], as points will always be an "empty" object.
