### ISSUE TITLE
How to add custom tooltip? a react native node 

### ISSUE THREAD

**Issue by idanlevi1** [FormidableLabs/victory-native-xl#176]
I use `CartesianChart` and I need a complex tooltip (view with border radios and shadow, with text inside a vertical line over the chart at this point)
I get an error when I try to render `View` inside ` {({ points, chartBounds, }) => ....`

example:
```
 {({ points, chartBounds, }) => (
            <>
              <Area
                points={points[!graph ? "amount" : 'interest']}
                y0={chartBounds.bottom}
                color="blue"
                curveType="catmullRom"
                animate={{ type: "timing" }}
              >
                <LinearGradient
                  start={{ x: 0, y: chartBounds.top }}
                  end={{ x: 0, y: chartBounds.bottom }}
                  colors={["#8DA", "#ffffff"]}
                />
              </Area>
              {isActive && (
                <View style={{width: 30, height: 20}}/>
              )} 
            </>
```

any help? 🙏🏼
```
 "react-native": "0.73.0",
 "victory-native": "^40.0.3"
 ```

**Comment by keithluchtel** [comment]
@idanlevi1 You cannot render React Native `View` or any other nodes within this render function. Within the render function you are drawing to the Skia canvas, and must use Skia elements.

See https://formidable.com/open-source/victory-native/getting-started#adding-a-tooltip for an example of adding a tooltip.
