### ISSUE TITLE
How to draw custom axes?

### ISSUE THREAD

**Issue by idanlevi1** [FormidableLabs/victory-native-xl#177]
The axes in the graph don't look good enough in my case,
X-axis not centered
my code:
```
 axisOptions={{
            font,
            tickCount: { x: 3, y: 3 },
            labelOffset: { x: 12, y: 8 },
            labelPosition: { x: "outset", y: "outset" },
            axisSide: { x: "bottom", y: "left" },
            formatXLabel: (ms) => moment(new Date(ms)).format("DD.MM.YY"),
            formatYLabel: (v) => `%${v}`,
          }}
```
<img width="287" alt="image" src="https://github.com/FormidableLabs/victory-native-xl/assets/21155847/05b5ac98-7d01-4940-840e-50f8c94fb3c8">

Is it possible to draw the axes in a custom way?

**Comment by keithluchtel** [comment]
Try using the `renderOutside` prop and custom drawing and see if that will meet your needs: https://formidable.com/open-source/victory-native/cartesian/cartesian-chart#renderoutside

**Comment by idanlevi1** [comment]
> Try using the `renderOutside` prop and custom drawing and see if that will meet your needs: https://formidable.com/open-source/victory-native/cartesian/cartesian-chart#renderoutside

Can you give me an example, please? because I don't know how to build the ranges and put the values (for example divide to 3 ticks..)

**Comment by hamadbhassan** [comment]
renderOutside provides you with the points and chartbounds props for you to use. Here is an example from my code of how I am using it. Hope it helps

In my case I had to make arabic text work so I had to do this workaround.

```
interface props {
  points: PointsArray,
  chartBounds: ChartBounds
}

const labelStyle = {
  color: Skia.Color('black'),
  fontSize: 12
}

function XAxisLabels({ points, chartBounds }: props): React.JSX.Element {
  // pre create the paragraph for performance reasons
  const paragraphs = useMemo((): { [key: string]: SkParagraph } => {
    const temp: { [key: string]: SkParagraph } = {}

    points.forEach(point => {
      'worklet'
      const label = String(point.xValue)
      const splitLabel = String(label).split('\n')
      const paragraph = Skia.ParagraphBuilder.Make({
        textDirection: SkTextDirection.RTL,
        textAlign: SkTextAlign.Center
      }).pushStyle(labelStyle)

      splitLabel.forEach((label, index) => {
        paragraph.addText(label)
        paragraph.addText('\n')
      })

      temp[label] = paragraph.build()

    })
    return temp
  }, [points])


  const labels = []

  points.forEach((point, index) => {
    const label = String(point.xValue)
    const x = point.x

    const width = 70

    labels.push(<Paragraph key={`${index} - ${label}`} paragraph={paragraphs?.[label]} x={x - (width / 2)}
                           y={chartBounds.bottom} width={width} />)
  })
  return <>
    {
      labels.map(x => x)
    }
  </>
}
```

**Comment by idanlevi1** [comment]
> renderOutside provides you with the points and chartbounds props for you to use. Here is an example from my code of how I am using it. Hope it helps
> 
> In my case I had to make arabic text work so I had to do this workaround.
> 
> ```
> interface props {
>   points: PointsArray,
>   chartBounds: ChartBounds
> }
> 
> const labelStyle = {
>   color: Skia.Color('black'),
>   fontSize: 12
> }
> 
> function XAxisLabels({ points, chartBounds }: props): React.JSX.Element {
>   // pre create the paragraph for performance reasons
>   const paragraphs = useMemo((): { [key: string]: SkParagraph } => {
>     const temp: { [key: string]: SkParagraph } = {}
> 
>     points.forEach(point => {
>       'worklet'
>       const label = String(point.xValue)
>       const splitLabel = String(label).split('\n')
>       const paragraph = Skia.ParagraphBuilder.Make({
>         textDirection: SkTextDirection.RTL,
>         textAlign: SkTextAlign.Center
>       }).pushStyle(labelStyle)
> 
>       splitLabel.forEach((label, index) => {
>         paragraph.addText(label)
>         paragraph.addText('\n')
>       })
> 
>       temp[label] = paragraph.build()
> 
>     })
>     return temp
>   }, [points])
> 
> 
>   const labels = []
> 
>   points.forEach((point, index) => {
>     const label = String(point.xValue)
>     const x = point.x
> 
>     const width = 70
> 
>     labels.push(<Paragraph key={`${index} - ${label}`} paragraph={paragraphs?.[label]} x={x - (width / 2)}
>                            y={chartBounds.bottom} width={width} />)
>   })
>   return <>
>     {
>       labels.map(x => x)
>     }
>   </>
> }
> ```

Great, thank you
