### ISSUE TITLE
Could we get a guide on how to use this with Expo?

### ISSUE THREAD

**Issue by DarynHolmes** [FormidableLabs/victory-native-xl#184]
### Question

I have been unable to get victory-native-xl working with a Expo app which I building with expo. 

Would it be possible to get a install guid for expo?

### Background Info/Attempts

I installed all the dependencies through "npx expo install". 

When it runs I get the following error: 

The current error I am getting is:
`Couldn't determine the version of the native part of Reanimated.`

I am using a standard expo generated app: npx create-expo-app victory-xl

My package.json 

`{
  "name": "victory-xl",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@shopify/react-native-skia": "0.1.221",
    "expo": "~50.0.2",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.2",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-reanimated": "~3.6.0",
    "react-native-svg": "14.1.0",
    "victory-native": "^40.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
`

babel.config.js 

`module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ["react-native-reanimated/plugin"]
  };
};
`

I would greatly appreciate a guid on how to set this up, thanks!

**Comment by zibs** [comment]
Hey @DarynHolmes thanks for raising this issue -- it looks like this is actually related to Reanimated/Expo 50.

You can see Expo acknowledge this here: https://github.com/expo/expo/issues/26534

In the meantime, I don't think should stop you from using this library: https://github.com/zibs/vnxl-expo you can see this example Expo project I bootstrapped still builds/lets me build charts currently. It should just be a warning, not a hard crash error.

We'll monitor and make sure to bump if we need to when the Reanimated/Expo fix is out.
