### ISSUE TITLE
Migration to Fabric 

### ISSUE THREAD

**Issue by maneesh-techversant** [FormidableLabs/victory-native-xl#188]
**Is your feature request related to a problem? Please describe.**
I'm wondering if someone is looking into migrating Victory native to use Fabric (i.e. the React Native New Architecture). I'm opening this issue to understand what's the current status of this.

**Describe the solution you'd like**
one of the open issues regarding this https://github.com/FormidableLabs/victory/issues/2484. I would like to use victory native in new projects following new architecture

**Comment by zibs** [comment]
Hey @maneesh-techversant - It's my understanding this already works with the new architecture since all the main deps do already too (skia, gesture handler, reanimated).

You can see this example repo I spun up: https://github.com/zibs/vnxl-rn
