### ISSUE TITLE
Stacked Area

### ISSUE THREAD

**Issue by jeromeMTX** [FormidableLabs/victory-native-xl#200]
### Question

Hi! thanks so much for all the improvements brought by the new version. Is there a way to do stacked area charts as it was possible in the previous version? For the moment, all our attempts have failed.

**Comment by idanlevi1** [comment]
@jeromeMTX Can you show an example of design?

**Comment by MichelBahl** [comment]
@idanlevi1 I think [this](https://commerce.nearform.com/open-source/victory/docs/victory-stack#victorystack
) kind of charts should be available in victory-native-xl too.

**Comment by zibs** [comment]
Anyone interested in this could help out by checking out https://github.com/FormidableLabs/victory-native-xl/pull/387 and seeing if it works for their use case!
