### ISSUE TITLE
Scatter chart with custom element?

### ISSUE THREAD

**Issue by lucksp** [FormidableLabs/victory-native-xl#205]
### Question

I am trying to migrate to the new version of Victory Native - we have a scatter chart that used `<VictoryChart><VictoryAxis /><VictoryScatter /></VictoryChart>`. 
Our Scatter component utilized the `dataComponent` prop to render a custom element.  

In migration to new version, the new Scatter component seems limited to props including the `shape`: `type ScatterShape = "circle" | "square" | "star";`

How would I render a custom element for Scatter?

### Background Info/Attempts

 This is our old code:

```js
 <VictoryChart
            domain={{
                x: domainX as DomainTuple,
                y: domainY as DomainTuple,
            }}
            domainPadding={{ x: 10, y: yDomainPadding }}
            height={148} // total height 186 - Victory build in parent padding on top & bottom
            padding={{ top: 0, bottom: 8, right: 48, left: onlyNV ? 0 : 48 }}
            width={chartWidth}
        >
            <VictoryAxis
                dependentAxis
                domain={domainY as DomainTuple}
                maxDomain={ticksValues[ticksValues.length - 1]}
                minDomain={ticksValues[0]}
                style={{
                    axis: { stroke: 'transparent' },
                    tickLabels: {
                        fill: theme.colors.khaki[600],
                        fontFamily: 'Inter_700Bold',
                        fontSize: 10,
                    },
                }}
                tickCount={dataWithNV.length}
                tickFormat={y => {
                    return y === nvYear ? 'N.V.' : y;
                }}
                tickValues={ticksValues}
            />
            <VictoryAxis
                domain={domainX as DomainTuple}
                style={{
                    axis: { stroke: 'transparent' },
                    tickLabels: { fill: theme.colors.primary },
                }}
                tickFormat={() => ''}
            />
            <VictoryScatter
                data={dataWithNV}
                dataComponent={
                    <DataComponent currentWine={currentWine?.Vintage} />
                }
            />
        </VictoryChart>
```
which renders this:
![image](https://github.com/FormidableLabs/victory-native-xl/assets/15162169/2e578393-0d40-4d38-b4d4-bfcb4a3efbc1)

**Comment by masiddee** [comment]
Ah yeah, good catch here @lucksp. This looks to be a result of the switchover to VNXL, where we're essentially re-building classic VN from the ground up to make it much more streamlined for mobile.

I've marked this as an `enhancement` request, to bring this particular feature into parity with classic VN.

**Comment by zibs** [comment]
Hey @lucksp this should indeed already be possible. Take a look at the `Custom Drawing` (https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/custom-drawing.tsx) example inside the example app and you can draw whatever you want in there.

Here's a rough sketch at what you were going for in your post. It's a bit tricky to really nicely control text currently, but that's something that will improve when we move to Skia 1.0+. I think with your use-case of just having 3chars you'd be able to make something passable right now though! Might just have to hardcode some values.

```tsx
// create paint object
const rectBorderPaint = Skia.Paint();
rectBorderPaint.setStrokeWidth(2);
rectBorderPaint.setColor(Skia.Color("lightblue"));
rectBorderPaint.setStyle(PaintStyle.Stroke);

// replace the rendering `Points` with:

{
  points.stars.map(({ x, y }) => {
    return (
      <React.Fragment key={`point-${x}-${y}`}>
        <Rect
          x={x - 10}
          y={y! - 10}
          width={30}
          height={20}
          color={shapeColor}
          paint={rectPaint}
        />
        <Text
          text={x.toString()}
          x={x}
          y={y!}
          font={font}
          color={isDark ? appColors.text.dark : appColors.text.light}
        ></Text>
      </React.Fragment>
    );
  });
}
```

**Comment by zibs** [comment]
Closing this as I think this is currently possible, but there's probably room for improvement down the line, but let's cross that bridge when we get there!
