### ISSUE TITLE
Where there is only one data point, it triggers duplicate key error from react.

### ISSUE THREAD

**Issue by varem611** [FormidableLabs/victory-native-xl#207]
### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`)
"victory-native": "^40.0.4", 
**What version of React and React Native are you using?**
"victory-native": "^40.0.4", 
**What version of Reanimated and React Native Skia are you using?**
    "@shopify/react-native-skia": "0.1.221",
    "react-native-reanimated": "~3.6.2",
**Are you using Expo or React Native CLI?**
Expo
**What platform are you on?** (e.g., iOS, Android)
Both
### Describe the Problem
When using the CartesianChart and there is only one data point and the axisOption prop is being used, react will throw an error indicating a duplicate key e.g.,

Error
Encountered two children with the same key, `x-tick-{x value}`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

```javascript
<CartesianChart
  chartPressState={[state]}
  data={[ // where there is only one data point and axisOptions
    {
      x: 10,
      y: 30,
    },
  ]}
  xKey="x"
  yKeys={["y"]}
  axisOptions={{
    font,
  }}
>
  {({ points, chartBounds }) => {
    return (
      ...
    );
  }}
</CartesianChart>
```

**Expected behavior:** [What you expect to happen]

- I would expect it not to throw this duplicate key error and for documentation to describe the limitation (.e.g., indicate the min length of data array) and for the component to return a descriptive error. 
- Nice to have: a Prop that behaves similar to the FlatLists's ListEmptyComponent Prop(https://reactnative.dev/docs/flatlist#listemptycomponent) where there is not enough data.

**Actual behavior:** [What actually happens]
As described above
### Additional Information
Really enjoying your lib so far, great work!

**Comment by masiddee** [comment]
Hey @varem611, thanks for sharing this! I can confirm this is a bug. I'm curious as to what might be causing this, so I'll take a closer look.

And I like your idea of gracefully handling any situation like this moving forward.

**Comment by varem611** [comment]
Not sure of the cause, how are you calculating the start and end points for the x labels?

Is the code creating duplicate labels where the min / max or start and end point of the x labels are the same as a result of there only being one data point?
