### ISSUE TITLE
fixed y axis values

### ISSUE THREAD

**Issue by flexbox** [FormidableLabs/victory-native-xl#210]
### Question
Is there a way to have fixed values to keep consistency between multiple charts?
like Y axis always between -12 and 12 ?

### Background Info/Attempts

**Expected** 

_Example:_ `axisYMin: -12, axisYMax: 12`

![CleanShot 2024-03-13 at 11 19 00@2x](https://github.com/FormidableLabs/victory-native-xl/assets/360936/7053a3b6-6e53-4ea8-b26f-15942df97549)

**Reality**
| Chart One | Chart Two |
|--------|--------|
| _Example:_ `axisYMin: -6, axisYMax: 0` | _Example:_ `axisYMin: -3, axisYMax: 0` |
| ![CleanShot 2024-03-13 at 11 16 44@2x](https://github.com/FormidableLabs/victory-native-xl/assets/360936/587bee19-0b8d-4377-ba5c-bef461889218) | <img width="412" alt="image" src="https://github.com/FormidableLabs/victory-native-xl/assets/360936/8b83916c-e84a-43b7-8d1c-beaa78425834"> | 

I am looking for a way to "force" values to render the chart event there is no data associated on this area.

**Comment by masiddee** [comment]
Hey @flexbox! If I understand what you are asking, the `domain` property on the `CartesianChart` component should resolve this by allowing you to explicitly set the min/max domains for both your x and y axis.

You can find more documentation on its implementation here: https://commerce.nearform.com/open-source/victory-native/cartesian/cartesian-chart#domain

**Comment by flexbox** [comment]
@masiddee indeed 

fixed with 

```
      <CartesianChart
        domainPadding={{ left: 12, right: 12, top: 16, bottom: 16 }}
        xKey="hz"
        yKeys={["db"]}
        domain={{ y: [-6, 6] }}
        axisOptions={{
          font,
          lineColor: gridColor,
          labelColor: color,
          formatXLabel: (x) => `${x}Hz`,
          formatYLabel: (y) => `${y}dB`
        }}
        data={data}
      >
```

![CleanShot 2024-03-15 at 16 04 17](https://github.com/FormidableLabs/victory-native-xl/assets/360936/81b34ea1-13f1-45aa-a656-b3ffb6c3a9e8)


Thank you 🚀

**Comment by masiddee** [comment]
Awesome! Glad to hear that worked for you!
