### ISSUE TITLE
Error: Unexhaustive handling for BVLinearGradient  This error is located at:     in Unknown (created by CartesianChart)

### ISSUE THREAD

**Issue by MarkJackson1997** [FormidableLabs/victory-native-xl#214]
### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`)
^40.0.4

**What version of React and React Native are you using?**
  "react": "18.2.0",
    "react-native": "0.72.6",

**What version of Reanimated and React Native Skia are you using?**
 "react-native-reanimated": "^3.8.0",
     "@shopify/react-native-skia": "^1.0.2",

**Are you using Expo or React Native CLI?**
React Native CLI

**What platform are you on?** (e.g., iOS, Android)
iOS and Android

### Describe the Problem

Getting this error when running example BarChart Code.
https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/bar-chart.tsx

Error: Unexhaustive handling for BVLinearGradient

This error is located at:
    in Unknown (created by CartesianChart)

### Additional Information

  <View style={{
        flex:1
       }}>
         <View style={{
          height:3000
         }}>
          <CartesianChart
            xKey="month"
            padding={5}
            yKeys={["listenCount"]}
            domainPadding={{ left: 50, right: 50, top: 30 }}
            domain={{ y: [0, 100] }}
            axisOptions={{
              font,
              tickCount: 5,
              formatXLabel: (value) => {
                const date = new Date(2023, value - 1);
                return date.toLocaleString("default", { month: "short" });
              },
              lineColor: "#d4d4d8",
              labelColor: "#d4d4d8",
            }}
            data={data}
          >
            {({ points, chartBounds }) => {
              return (
                <>
                  <Bar
                    points={points.listenCount}
                    chartBounds={chartBounds}
                    animate={{ type: "spring" }}
                    innerPadding={innerPadding}
                    roundedCorners={{
                      topLeft: roundedCorner,
                      topRight: roundedCorner,
                    }}
                  >
                    <LinearGradient
                      start={vec(0, 0)}
                      end={vec(0, 400)}
                      colors={["#a78bfa"]}
                    />
                  </Bar>
                </>
              );
            }}
          </CartesianChart>
        </View>
      </View>

**Comment by zibs** [comment]
My hunch is that `height:3000` is causing some problems somewhere. I tried to recreate with 2000 and it seems to render still, but I don't quite understand the use case for such a tall chart?

**Comment by MarkJackson1997** [comment]
I tried with height 300 as well but still it creating issue.
