### ISSUE TITLE
Error: Unexhaustive handling for BVLinearGradient This error is located at: in Unknown (created by CartesianChart)

### ISSUE THREAD

**Issue by MarkJackson1997** [FormidableLabs/victory-native-xl#215]
### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`)
^40.0.4

**What version of React and React Native are you using?**
"react": "18.2.0",
"react-native": "0.72.6",

**What version of Reanimated and React Native Skia are you using?**
"react-native-reanimated": "^3.8.0",
"@shopify/react-native-skia": "^1.0.2",

**Are you using Expo or React Native CLI?**
React Native CLI

**What platform are you on?** (e.g., iOS, Android)
iOS and Android

### Describe the Problem
Getting this error when running example BarChart Code.
https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/bar-chart.tsx

Error: Unexhaustive handling for BVLinearGradient

This error is located at:
in Unknown (created by CartesianChart)

### Additional Information
```
<LinearGradient
                      start={vec(0, 0)}
                      end={vec(0, 400)}
                     colors={["#4c669f", "#3b5998"]}
                    />
```
above line of code is creating issue as per my understanding.after commenting this line not getting error.
But i need to add gradient color in chart.

```
 <View style={{
 flex:1
       }}>
         <View style={{
          height:150
         }}>
          <CartesianChart
            xKey="month"
            padding={5}
            yKeys={["listenCount"]}
            domainPadding={{ left: 50, right: 50, top: 30 }}
            domain={{ y: [0, 100] }}
            axisOptions={{
              font,
              tickCount: 5,
              formatXLabel: (value) => {
                const date = new Date(2023, value - 1);
                return date.toLocaleString("default", { month: "short" });
              },
              lineColor: "#d4d4d8",
              labelColor: "#d4d4d8",
            }}
            data={data}
          >
            {({ points, chartBounds }) => {
              return (
                <>
                  <Bar
                    points={points.listenCount}
                    chartBounds={chartBounds}
                    animate={{ type: "spring" }}
                    innerPadding={innerPadding}
                    roundedCorners={{
                      topLeft: roundedCorner,
                      topRight: roundedCorner,
                    }}
                  >
                    <LinearGradient
                      start={vec(0, 0)}
                      end={vec(0, 400)}
                     colors={["#4c669f", "#3b5998"]}
                    />
                  </Bar>
                </>
              );
            }}
          </CartesianChart>
        </View>
      </View> 
```

<img width="365" alt="Screenshot 2024-03-16 at 2 43 54 PM" src="https://github.com/FormidableLabs/victory-native-xl/assets/39664330/bf35f55a-4d97-4b84-8ba8-e13381db3330">

**Comment by MarkJackson1997** [comment]
Whatever height i takes i giving this error.
If anyone know how to fix this then please help.

**Comment by keithluchtel** [comment]
@MarkJackson1997 I just tried reproducing this issue and am not able to. Can you create a sample repository and share?

**Comment by MarkJackson1997** [comment]
Issued is with LinearGradient.

**Comment by lucksp** [comment]
> Issued is with LinearGradient.



@MarkJackson1997 
I also have the issue where the [supporting docs ](https://commerce.nearform.com/open-source/victory-native/docs/cartesian/guides/custom-bars#:~:text=%3CLinearGradient%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20start%3D,a78bfa50%22%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D) do not work in app.  

My snippet:

```js
{({ points, chartBounds }) => {
        return points.count.map((point, i) => {
          const gradient =
            i === 0 ? ['#f472b6', '#be185d'] : ['#a5f3fc', '#0891b2'];

          return (
            <Bar
              key={point.xValue}
              animate={{ type: 'spring' }}
              points={points.count}
              barCount={points.count.length}
              barWidth={Dimensions.get('screen').width / 20}
              chartBounds={chartBounds}
              roundedCorners={{
                topLeft: 8,
                topRight: 8,
              }}
            >
              <Text font={font} text={point.xValue.toString()} />
              <LinearGradient
                start={vec(0, 0)}
                end={vec(0, 750)} //i thought changing this would help but it does not 
                colors={gradient}
              />
            </Bar>
          );
        });
```

In the end, I am only getting a single color rendered

**Comment by keithluchtel** [comment]
@lucksp if you look at the `Bar Chart Custom Bars` example in the example app, I'm seeing Linear Gradient work on the bars.

If you clone this repo and run `yarn dev:example` you can launch the example app and play around.

**Comment by keithluchtel** [comment]
@lucksp I just tested it again and it seems to be working just fine for me on `main` branch

https://github.com/user-attachments/assets/32ace5ae-37b7-4516-a4f0-ca5521926c3c
