### ISSUE TITLE
Error while running example app('RNSkiaModule' could not be found)

### ISSUE THREAD

**Issue by MarkJackson1997** [FormidableLabs/victory-native-xl#216]
### Question
<img width="1069" alt="Screenshot 2024-03-17 at 4 23 48 PM" src="https://github.com/FormidableLabs/victory-native-xl/assets/39664330/3c83421d-8bb9-4b9a-9ab9-beb4385d20a1">

I am using this library in my project.For this i am trying to run example project.But it gives same error for both android and ios platform.

In example app getting this error
**Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNSkiaModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes** 
### Background Info/Attempts

 "@expo/vector-icons": "^13.0.0",
    "@gorhom/bottom-sheet": "^4",
    "@react-native-community/slider": "4.4.2",
    "@react-native-segmented-control/segmented-control": "^2.4.2",
    "@shopify/react-native-skia": "0.1.196",
    "date-fns": "^2.30.0",
    "expo": "~49.0.6",
    "expo-asset": "~8.10.1",
    "expo-constants": "~14.4.2",
    "expo-haptics": "~12.4.0",
    "expo-image": "^1.3.2",
    "expo-linking": "~5.0.2",
    "expo-router": "2.0.0",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-fast-compare": "^3.2.2",
    "react-native": "0.72.3",
    "react-native-dark": "^0.1.3",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-wheel-color-picker": "^1.2.0",
    "expo-splash-screen": "~0.20.5"

**Comment by Bima42** [comment]
I had the same issue recently, and I've fixed it by doing this : 
- Run `npx expo install --fix` : this command will reinstall versions of packages that work properly together
- After that, I had an issue with `react-native-reanimated`, something like `Property _measure does not exist`. I have fix this one by : 
  - deleting `node_modules`
  - removing the package from `package.json` and from `babel.config.js`
  - reinstalling packages with `npm install`
  - add `react-native-reanimated` with `npx expo install react-native-reanimated` 
  - add `react-native-reanimated` on `babel.config.js`. Be careful here, the `react-native-reanimated` must to be the **LAST OF PLUGINS ARRAY** in your config

Hope this help !

**Comment by MarkJackson1997** [comment]
@Bima42 
thanks this 3 things is worked for me.
1).npx expo install --fix
2).After that put react-native-reanimated in last inside plugin array.
3).npx expo start --clear
