### ISSUE TITLE
Help understanding formatXLabel and formatYLabel

### ISSUE THREAD

**Issue by SFJT-97** [FormidableLabs/victory-native-xl#226]
This is what I'm getting 
![Simulator Screenshot - iPhone 15 Pro Max - 2024-03-25 at 00 50 04](https://github.com/FormidableLabs/victory-native-xl/assets/101666729/022f32d2-0035-4cdb-88fe-8f2f2d2df519)

I've been looking for examples and reading the documentation, but can't figure how to make formatXLabel and formatYLabel to work. Once I hit the black charts from the example, I got stuck since I cant figure out how to use the format labels in my use case; any help would be welcome, thanks in advance.

This is my data.js

``export const accidents = [
    {
        type: "Electrical",
        amount: 10
    },
    {
        type: "Infrastructural",
        amount: 5
    },
    {
        type: "Vehicular",
        amount: 7
    },
    {
        type: "Misuse",
        amount: 15
    },
    {
        type: "Incidental",
        amount: 4
    },
    {
        type: "Other",
        amount: 8
    }
]``

this is my chart.jsx

```import { View } from "react-native"
import { Bar, CartesianChart } from "victory-native"
import {  useFont } from "@shopify/react-native-skia"

import { accidents } from './data'

export default function Chart() {

    const font = useFont()

  return (

    <View style={{ width: 400, height: 300 }}>
        <CartesianChart
        data={accidents}
        xKey="type"
        yKeys={["amount"]}
        domainPadding={{ left: 50, right: 50, top: 30 }}
        axisOptions={{ 
            font,
            formatXLabel,
            formatYLabel
        }}
        >
        {({ points, chartBounds }) => (
            <Bar
            chartBounds={chartBounds}
            points={points.amount}
            roundedCorners={{
                topLeft: 5,
                topRight: 5,
            }}
            >
            </Bar>
        )}
        </CartesianChart>
    </View>
  )
}

**Comment by TomCorvus** [comment]
Hi @SFJT-97,

`useFont` hook needs param like font you want to use and size.
https://commerce.nearform.com/open-source/victory-native/cartesian/cartesian-chart#example

**Comment by zibs** [comment]
Thanks @TomCorvus -- I'm going to assume that resolves this issue.
