### ISSUE TITLE
Getting Started Guide - showing blank chart

### ISSUE THREAD

**Issue by jawknees** [FormidableLabs/victory-native-xl#228]
### Prerequisites

- [x] I have searched the open [issues](https://www.github.com/FormidableLabs/victory-native-xl/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/victory-native-xl/docs) before asking a question
- [x] I am using the latest version of victory-native-xl

### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`)
```
40.1.0
```

**What version of React and React Native are you using?**
```
    "react": "18.2.0",
    "react-native": "0.71.17",
```

**What version of Reanimated and React Native Skia are you using?**
```
    "react-native-reanimated": "^3.8.1",
    "@shopify/react-native-skia": "^1.0.4",
```

**Are you using Expo or React Native CLI?**
```
React Native CLI
```

**What platform are you on?** (e.g., iOS, Android)
```
Android, for now
```

### Describe the Problem
I'm starting out on using the library. tried the getting started guide on android, but I can't get my app to display anything. Tried to find something within the issues board, but nothing about chart showing blank. Installations were good, there were warnings with CMake but the build came through successfully.

**Steps to Reproduce**
Just follow the Getting started guide. Like properly and directly follow the Getting Started guide

Here's a sample code of what I did. Just really followed the getting started guide with some little tweaks:

```
import { View, Text, SafeAreaView } from 'react-native'
import React, { useEffect } from 'react'
import { CartesianChart, Line } from 'victory-native';

const generateRandomNumbers = (length) => {
    let randomNumbers = [];
  
    for (let i = 0; i < length; i++) {
        
        let randomNumber = Math.floor(Math.random() * 100);

        randomNumbers.push({ x: randomNumber, y: i });
    }
  
    // Return the array of objects
    console.log("generated random numbers", randomNumbers);
    return randomNumbers;
};

const AppMain = ({navigation, route}) => {

    const DATA2 = generateRandomNumbers(31);

    useEffect(() => {
        console.log('mounted');
        
        return(() => {
            console.log('unmounted');
        });
    }, [navigation]);

    return (
        <SafeAreaView style={{flex: 1}} >
            <View style={{height: 500, borderColor: 'black', borderWidth: 1,}} >
                <CartesianChart data={DATA2} xKey={"x"} yKeys={["y"]}
                >
                    {({ points }) => (
                        <Line 
                            points={points.y}
                            color="red"
                            strokeWidth={3}
                            // animate={{type: 'timing', duration: 200}}
                        />
                    )}
                </CartesianChart>
                {/* <Text>Something</Text> */}
            </View>
        </SafeAreaView>
    )
}

export default AppMain
```

**Expected behavior:** [What you expect to happen]
```
Should show the sample chart that was given with the example image within the guide.
```

**Actual behavior:** [What actually happens]
```
Blank. Nothing. I can show you a screenshot. It has a given border to where the chart should display.
```
![image](https://github.com/FormidableLabs/victory-native-xl/assets/87589038/c0cb62f8-1f5a-45f9-8de8-7a2153fd90ce)

### Additional Information

not really much, this is just a fresh install. It's just that i'm using react native 0.71.17 version. But I think that shouldn't be an issue. Since I've read in some articles that you need to have 0.71.x to get most libraries working with RN. PLUS, there's was not any issues with building the android app

not really sure what i'm missing here :/

**Comment by jawknees** [comment]
Just found my problem, my bad. This code was messing with my render. As I saw this as a fix with hermes engine. tried removing it and now the lines are here.

```
 Array.prototype.at = (index) => {
     if(index > (this.length - 1)) {
         return undefined;
     } 
     return this[index];
 }```

remove this if you're >= RN 0.71.x

**Comment by jawknees** [comment]
Just found my problem, my bad. This code was messing with my render. As I saw this as a fix with hermes engine. tried removing it and now the lines are here.

```
 Array.prototype.at = (index) => {
     if(index > (this.length - 1)) {
         return undefined;
     } 
     return this[index];
 }
 ```

remove this if you're >= RN 0.71.x

**Comment by JoelNgiamKeeYong** [comment]
@jawknees Was this code added by you manually? Or was it shipped with the Victory Native XL package? Because I have the same issue with you and I am using Expo
