### ISSUE TITLE
How to control ticks on axes?

### ISSUE THREAD

**Issue by vdddslep** [FormidableLabs/victory-native-xl#234]
### Question

I am migrating from a legacy version of the library and I have a simple task: I need to display only the minimum and maximum values from my data on the axes and nothing more, how could I achieve this?

Example: 
![Screenshot 2024-04-11 at 00 41 26](https://github.com/FormidableLabs/victory-native-xl/assets/25424315/f0d47dc5-30e4-4fa9-a27a-629636259ddc)

**Comment by zibs** [comment]
You could explore the options [here](https://commerce.nearform.com/open-source/victory-native/cartesian/cartesian-chart#axisoptions) and see if those help!

**Comment by vdddslep** [comment]
> You could explore the options [here](https://commerce.nearform.com/open-source/victory-native/cartesian/cartesian-chart#axisoptions) and see if those help!

I studied everything carefully and it seems that the new library is not as universal as the old one since it does not provide such flexible configuration of the displayed values on the axes

**Comment by keithluchtel** [comment]
> > You could explore the options [here](https://commerce.nearform.com/open-source/victory-native/cartesian/cartesian-chart#axisoptions) and see if those help!
> 
> I studied everything carefully and it seems that the new library is not as universal as the old one since it does not provide such flexible configuration of the displayed values on the axes

This is correct. This new version is a complete rewrite optimized for React Native. With that, we simply haven't had the time to add as extensive of configuration and chart types.

**Comment by fmmattioni** [comment]
Would love to have the ability to set tick values too, as in https://commerce.nearform.com/open-source/victory/docs/victory-axis#tickvalues

**Comment by fmmattioni** [comment]
on the same topic, is there a way to define the scale or scale type? I would like to apply the scale nice effect: https://d3js.org/d3-scale/linear#linear_nice

**Comment by masiddee** [comment]
Thanks for sharing! I'm going to spend a few cycles looking into how we might be able to implement this

**Comment by zibs** [comment]
I think this is resolved on latest -- see merged PR above for more!
