### ISSUE TITLE
ToolTip data formating

### ISSUE THREAD

**Issue by vdddslep** [FormidableLabs/victory-native-xl#235]
I need to display a graph of changes in the user's weight and the weight data is stored in the following form:

const date = [{weight: 74.389088, date: "Sat Apr 06 2024 00:40:33 GMT+0300"}, .....]

where is the weight in kilograms. 

In the CartesianChart component, I use the following code to format the data, which works well for my case:
   formatXLabel: (x)=>`${(new Date(x)).getDate()} ${format(x, 'MMM')}`,
   formatYLabel: (tick) => tickFormat(tick),
   
   
    function tickFormat(tick:number):string {
        if(tick == 0) {
            return "";
        }
        const value = userStore.getWeightInCurrentUnits(tick)
        if(value % 1 === 0) {
            return value.toString();
        } else {
            return value.toFixed(1) + " ";
        }
    }
    
    
   Now my task is to make a tooltip for the user by clicking on the chart and the task looks impossible:
   
   
   1) I tried the example from the documentation with animated props:
   
       const animatedDate = useAnimatedProps(()=> {
        return {
            text: state.x.value.value + "",
            defaultValue: '',
        }
    })
    
    but I can't format neither the date nor the user's weight according to the selected settings.
    Because In this case, using Date inside useAnimatedProps (which involves executing code in the worklet) violates one of Reanimated's key limitations: the use of native JavaScript objects like Date and global functions like Math etc.
    
    2) Okay, I decided to write my own tooltip component: 
    
     function ToolTip({ x, y, weight, date }: { x: SharedValue<number>; y: SharedValue<number>; weight:SharedValue<number>; date:SharedValue<string> }) {
        return (
            <View
                style={{ position: 'absolute', left: x.value, top: y.value, backgroundColor: 'white', padding: 4, borderRadius: 4 }}
            >
                <Text>Weight: {weight.value}</Text>
                <Text>Date: date.value</Text>
            </View>
        );
    }
    
    and now I've got ERROR:
    
    
 **ERROR  Error: Text nodes are not supported yet**
 
  >>>>>>> DEAD END <<<<<<<

**Comment by zibs** [comment]
The issue you're experience is because your tooltip is rendering normal RN elements. Anything rendered inside the `CartesianChart` is going to be rendered in a Skia canvas, so you'll have to use Skia elements, or redesign your UI and render your tooltip details elsewhere.

**Comment by vdddslep** [comment]
if I could use - Skia elements
Why do I need victory xl?

**Comment by keithluchtel** [comment]
@vdddslep Here is an example rendering a tooltip with text: https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/stock-price.tsx#L348

**Comment by vdddslep** [comment]
@keithluchtel Thank you
