### ISSUE TITLE
How to create Bar where one bar is styled differently? 

### ISSUE THREAD

**Issue by garygcchiu** [FormidableLabs/victory-native-xl#239]
### Question

I wanted to create something like this:

![IMG_0788](https://github.com/FormidableLabs/victory-native-xl/assets/19521762/bff00904-2a13-4a6f-8cbc-3350fe09a725)

Basically a bar chart, but one of the bars is styled differently, perhaps the `fill` and `stroke`. 

### Background Info/Attempts

Looking at `useBarPath` and the `Bar` component, I haven't been able to figure out a way where I can get the index of a given path. 

Is there a barebones example or guidance for how this can be achieved? 

Thanks!

**Comment by zibs** [comment]
Thanks @garygcchiu  -- I'm not sure if it's possible/straightforward right now, but I think that it should be. If I have the time I'll try to get something set up here.

**Comment by julian-gargicevich** [comment]
keen!

**Comment by iyansr** [comment]
Any update ser?

**Comment by Tukutlas** [comment]
@garygcchiu, were you able to implement the different color bars?

**Comment by garygcchiu** [comment]
@Tukutlas yes, I was able to just use the `color` prop on the Bar component, something like:

```
<CartesianChart
	data={chartData}
	xKey={"x"}
	yKeys={["y"]}
	...
>
	{({ points, chartBounds }) => {
		return points.y.map((p, i) => {
			return (
				<Bar
					barWidth={8}
					barCount={points.y.length}
					key={p.x}
					points={[p]}
					chartBounds={chartBounds}
					color={
						i === lastIndex
							? "#afafaf"
							: "transparent"
					}
					roundedCorners={{ topLeft: 3, topRight: 3 }}
				/>
			);
		});
	}}
</CartesianChart>
```
