### ISSUE TITLE
How to display a Pie.Chart for only one Pie.Slice

### ISSUE THREAD

**Issue by relez** [FormidableLabs/victory-native-xl#240]
Hi guys, in the data coming from the server, sometimes there is only 1 slice to show, in that case the chart is not showing, any reason why? Thanks!

**Comment by zibs** [comment]
Hey @relez -- If you can you provide something reproducible/example code/more details, I can take a closer look. If you clone and run the example app inside this repo, we do have Pie chart examples that run with only 1 data point, so it should be working...but let me know!

**Comment by relez** [comment]
Thank you @zibs for your reply, I was sending the array of data with some items with value as 0. What I did was to separate the data array and legends and it solves the problem.
