### ISSUE TITLE
is it possible multiple line color divide section?

### ISSUE THREAD

**Issue by LESANF** [FormidableLabs/victory-native-xl#241]
## Question

![스크린샷 2024-04-23 오후 3 52 09](https://github.com/FormidableLabs/victory-native-xl/assets/54767632/29efbc8b-eb33-44fa-a7b9-dfdc5194c388)

Less than 70, greater than 70 and less than 140, greater than 140

Prior to version 40, VictoryLine was cut into sections and used by returning multiple components. 

However, performance was too low on AOS.

On the contrary, the performance of AOS has improved in the xl version

but I'm not sure how to give color by section. Is it possible to implement it like that?

**Comment by zibs** [comment]
Hey @LESANF  -- It's possibly possible depending on how you structure your data. 

I've used the `line-chart` example from the example repo here:

```tsx
<>
              <Line
                points={points.sales}
                curveType={curveType}
                color={"blue"}
                strokeWidth={strokeWidth}
                animate={{ type: "spring" }}
              />
              <Line
                points={points.sales.filter(
                  (v) => v.xValue < 7 && v.xValue > 3,
                )}
                curveType={curveType}
                color={"red"}
                strokeWidth={strokeWidth}
                animate={{ type: "spring" }}
              />
            </>
```

You can see I added a second `Line` component and am filtering the values I want to colorize. I'm filtering by xValues for simplicity, but you could filter via yValues or a combination of both.

![Simulator Screenshot - iPhone 15 Pro - 2024-04-23 at 14 00 36](https://github.com/FormidableLabs/victory-native-xl/assets/1131641/7b39eb23-8f79-4f8a-ada7-a64bdcf7bed3)

**Comment by LESANF** [comment]
@zibs  You’re awesome! That’s very kind of you.
