### ISSUE TITLE
Possible to combine bar and line in same chart?

### ISSUE THREAD

**Issue by jannejava** [FormidableLabs/victory-native-xl#258]
### Question

Is it possible to combine bars and a line in the same chart. Eg I would like to show energy consumption as bars for each day and at the same time show temperatures as a line. In this way to can see if there is a correlation. 

### Background Info/Attempts

Tried bar groups and also adding line to chartesian chart with no luck. 

Scanned the internet and documentation for examples too. 

Thanks in advance!

**Comment by jannejava** [comment]
Thanks for the clarification, I got it! 

Just a quick question. Can you have multiple y-axis with different scales if there is a significant difference in value ranges? For example if consumption is sales is between 5000-10000 (bars) and outside temperature (line) is between -10-20 degrees.

**Comment by zibs** [comment]
I don't think we support multiple y-axes yet sorry! Feel free to make an issue requesting that and I can tag it as an enhancement/see where it fits on the roadmap.

**Comment by zibs** [comment]
Closing since we addressed the initial issue!
