### ISSUE TITLE
Pie chart doesn't render when only one data object is nonzero

### ISSUE THREAD

**Issue by stevengoldberg** [FormidableLabs/victory-native-xl#264]
Describe Your Environment
What version of victory-native-xl are you using? 40.1.1

What version of React and React Native are you using? react 18.2.0, react-native 0.73.6

What version of Reanimated and React Native Skia are you using? reanimated 3.8.1, skia 0.1.221

Are you using Expo or React Native CLI? expo

What platform are you on? (e.g., iOS, Android) iOS

### Describe the Problem

When a pie chart contains only one non-zero value, nothing is rendered. To reproduce, pass a `data` array which contains exactly 1 non-zero value as well as 1 or more zero values to the `PieChart` component. e.g.:

```const data = [
            {
                label: 'foo',
                color: 'red',
                value: 10,
            },
            { label: 'bar', color: 'blue', value: 0 },
            { label: 'baz', color: 'green', value: 0 },
        ]

```
**Expected behavior:** [What you expect to happen]

I should see a red circle.

**Actual behavior:** [What actually happens]

<img width="346" alt="image" src="https://github.com/FormidableLabs/victory-native-xl/assets/2230992/79b79175-f152-4941-bf52-9da1d18ec9c1">

**Comment by zibs** [comment]
Thanks @stevengoldberg I can confirm this is a bug, I'll try to get a fix out soon.
