### ISSUE TITLE
Bar path select one bar

### ISSUE THREAD

**Issue by LukeMauve-Lawrence** [FormidableLabs/victory-native-xl#265]
Is it possible to select a single bar and change it's styling accordingly?
I want to highlight a bar and get data based on the user pressing one.
I can get the value from the useChartPressState, but I can't figure out how to change the styling for a single bar...

**Comment by zibs** [comment]
Unfortunately, it's not currently possible to style a single bar differently, but this relates to #239 as well -- I think it's something we'd like to support but just haven't got there yet!

**Comment by zibs** [comment]
Going to close and track this amongst #239
