### ISSUE TITLE
How can I get the Values of the XY axis and Display it in Text Component - React Native

### ISSUE THREAD

**Issue by inthisar-hamza** [FormidableLabs/victory-native-xl#267]
![Untitled](https://github.com/FormidableLabs/victory-native-xl/assets/13174985/6b06a4e6-7b73-469a-b2ea-adef11e07008)

### Question

How can I get the points of the XY axis and Display it in Text Component,
I havent learnt reanimated yet, It's helpful if there are example.

### Background Info/Attempts

`<CartesianChart
                data={
                  finalGraphData.length == 0
                    ? [
                        {
                          key: "",
                          value: 0,
                        },
                        {
                          key: "",
                          value: 0,
                        },
                        {
                          key: "",
                          value: 0,
                        },
                      ]
                    : finalGraphData.length <= 1
                    ? [...finalGraphData, ...finalGraphData, ...finalGraphData]
                    : finalGraphData
                }
                xKey="key"
                yKeys={["value"]}
                chartPressState={state}
                axisOptions={{
                  font,
                  formatYLabel(label): string {
                    return `${amountFormatChart(label, 0)}`;
                  },
                  formatXLabel(label): string {
                    return `${label ? label : ""}`;
                  },
                  labelColor: style.text,
                  lineColor: {
                    grid: {
                      x: colorScheme == "dark" ? "#656566" : "#C7C8C9",
                      y: colorScheme == "dark" ? "#656566" : "#C7C8C9",
                    },
                    frame: style.background,
                  },
                }}
                padding={15}
                domain={{
                  x: [
                    0,
                    selectedPeriod == "Month"
                      ? finalGraphData.length - 1
                      : finalGraphData.length,
                  ],
                }}
                domainPadding={{
                  left: 1,
                  right: 1,
                  top: 10,
                  bottom: 10,
                }}
              >
                {({ points, chartBounds }) => {
                  return (
                    <>
                      <Line
                        points={points?.value}
                        color={style.text}
                        strokeWidth={2}
                        curveType={"bumpX"}
                        animate={{
                          type: "spring",
                        }}
                      />
                      {isActive && (
                        <ToolTip
                          x={state.x?.position}
                          y={state.y?.value?.position}
                        />
                      )}
                    </>
                  );
                }}
              </CartesianChart>`

**Comment by inthisar-hamza** [comment]
Example was Found on Repository

**Comment by dionator** [comment]
> Example was Found on Repository

Do you mind pointing me to the link of the example you found to solve this?

**Comment by inthisar-hamza** [comment]
@dionator [link](https://github.com/FormidableLabs/victory-native-xl/tree/main/example)
