### ISSUE TITLE
'Pie.Chart' cannot be used as a JSX component. Return type 'Element[]'

### ISSUE THREAD

**Issue by CastroDF** [FormidableLabs/victory-native-xl#278]
### Describe Your Environment

**What version of victory-native-xl are you using?** `0.72.5`

**What version of React and React Native are you using?** `40.2.0`

**What version of Reanimated and React Native Skia are you using?** `3.11.0 && 1.2.3`

**Are you using Expo or React Native CLI?** `React Native CLI`

**What platform are you on?** `iOS & Android`

### Describe the Problem

I've copied the PieChart example at [example/app/pie-chart.tsx](https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/pie-chart.tsx) and I'm receiving the following error:
<img width="400" alt="Screenshot 2024-05-18 at 22 18 47" src="https://github.com/FormidableLabs/victory-native-xl/assets/59264493/b0e91933-d7ef-4224-965b-c6639ec0923e">

These are the types of the `Pie`, installed at `node_modules/victory-native/dist/pie/index.d.ts` (Sorry for the chunk of code):
```
<reference types="react" />
import { type PieSliceData } from "./PieSlice";
declare const Pie: {
    Chart: (props: {
        children?: ((args: {
            slice: PieSliceData;
        }) => import("react").ReactNode) | undefined;
        innerRadius?: string | number | undefined;
    }) => import("react").JSX.Element[];
    Slice: (props: Partial<Omit<import("@shopify/react-native-skia").PathProps, "path" | "color">>) => import("react").JSX.Element;
    SliceAngularInset: (props: {
        angularInset: import("./PieSliceAngularInset").PieSliceAngularInsetData;
    } & Partial<Omit<import("@shopify/react-native-skia").PathProps, "path" | "color">>) => import("react").JSX.Element | null;
};
export { Pie, type PieSliceData };
```

**Expected behavior:** 
I'm expecting the example to be working right out of the box.

**Actual behavior:**
I can't compile 😭

### Additional Information
I think that error makes sense given the types we have

**Comment by zibs** [comment]
This should be working....and it does seem fine in the example app repo. Can you clarify what's going on with your `insetWidth` and `insetColor`, as TS seems to be erroring on those which might be cascading the error? Otherwise, it might be your TS version or something potentially.

**Comment by CastroDF** [comment]
@zibs First of all, thanks for answering, the Pie Chart is working like a charm, I was missing some heights. About the `insetWidth` and `insetColor`, I've realized they were missing at the moment of the screenshot, but the error with the return type is still there. About the TS error, I've disabled typescript on that line, but it basically says that a return type 'Element[]' is not a valid JSX element

**Comment by zibs** [comment]
Unfortunately, I think this might be an issue with your environment, and not a problem with the package as all the examples seem to be working currently, but let me know if that's not the case!

**Comment by jonnyggao** [comment]
@zibs I am getting the same problem. Pie.Chart returning a list instead of a single component is strange. Perhaps the jsx that Pie.Chart returns should be wrapped in a fragment to be more accommodating to different environments.

**Comment by mMarcos208** [comment]
Same here.

**Comment by CastroDF** [comment]
> Same here.

@jonnyggao @mMarcos208 I suggest disabling TypeScript checks on that specific file/line. Based on my understanding, `Element[]` is not allowed to be returned in a JSX component, which is why this issue arises. While this approach might seem unconventional, it should resolve the error. If you disable the TypeScript checks on that line, the code should function as expected.
