### ISSUE TITLE
It’s possible build pie chart with animation in this version?

### ISSUE THREAD

**Issue by Kaique292** [FormidableLabs/victory-native-xl#279]
I’m using Expo version 51. I want to build a donut chart like this in image, i want with animation when data changes. Its possible with this library? 

![IMG_7809](https://github.com/FormidableLabs/victory-native-xl/assets/42048798/5c4b0dd9-6833-4e2d-accc-b9cc8296fd47)

**Comment by zibs** [comment]
We don't support animations on the Pie charts yet, but it is on the roadmap.
