### ISSUE TITLE
Replace deprecated `SkFont.getTextWidth` in favor of `SkFont.measureText` to fix alignment issues on labels and axis padding

### ISSUE THREAD

**Issue by owattenmaker** [FormidableLabs/victory-native-xl#282]
Hello,

I've noticed a spacing issue which has to do with the use of `getTextWidth` instead of `measureText` to calculate width.
The former function is deprecated and it seems like it has buggy behavior (which may be the reason for the deprecation. 

Here's an example of without the fix:
<img width="204" alt="image" src="https://github.com/FormidableLabs/victory-native-xl/assets/10779381/04773caf-9e91-4878-9c34-49dc0aae2043">
Notice how the bottom label is misaligned. 

Now if we replace all instances of `getTextWidth` with `measureText`, the alignment issue fixes itself:
<img width="164" alt="image" src="https://github.com/FormidableLabs/victory-native-xl/assets/10779381/6f546897-f358-4a23-b369-9078ed00dfa8">

This is the diff generated by patch-package:

```diff
diff --git a/node_modules/victory-native/src/cartesian/components/CartesianAxis.tsx b/node_modules/victory-native/src/cartesian/components/CartesianAxis.tsx
index 183e514..a8be7d7 100644
--- a/node_modules/victory-native/src/cartesian/components/CartesianAxis.tsx
+++ b/node_modules/victory-native/src/cartesian/components/CartesianAxis.tsx
@@ -125,7 +125,7 @@ export const CartesianAxis = <
     : yScale.ticks(yTicks);
   const yAxisNodes = yTicksNormalized.map((tick) => {
     const contentY = formatYLabel(tick as never);
-    const labelWidth = font?.getTextWidth?.(contentY) ?? 0;
+    const labelWidth = font?.measureText(contentY).width ?? 0;
     const labelY = yScale(tick) + fontSize / 3;
     const labelX = (() => {
       // left, outset
@@ -178,7 +178,7 @@ export const CartesianAxis = <
   const xAxisNodes = xTicksNormalized.map((tick) => {
     const val = isNumericalData ? tick : ix[tick];
     const contentX = formatXLabel(val as never);
-    const labelWidth = font?.getTextWidth?.(contentX) ?? 0;
+    const labelWidth = font?.measureText(contentX).width ?? 0;
     const labelX = xScale(tick) - (labelWidth ?? 0) / 2;
     const canFitLabelContent =
       yAxisPosition === "left" ? labelX + labelWidth < x2r : x1r < labelX;
diff --git a/node_modules/victory-native/src/cartesian/utils/transformInputData.ts b/node_modules/victory-native/src/cartesian/utils/transformInputData.ts
index b56dbc0..8b5f145 100644
--- a/node_modules/victory-native/src/cartesian/utils/transformInputData.ts
+++ b/node_modules/victory-native/src/cartesian/utils/transformInputData.ts
@@ -183,7 +183,7 @@ export const transformInputData = <
   // Else, we find min / max of y values across all yKeys, and use that for y range instead.
   const ixMin = asNumber(domain?.x?.[0] ?? tickDomainsX?.[0] ?? ixNum.at(0)),
     ixMax = asNumber(domain?.x?.[1] ?? tickDomainsX?.[1] ?? ixNum.at(-1));
-  const topYLabelWidth = axisOptions?.font?.getTextWidth(topYLabel) ?? 0;
+  const topYLabelWidth = axisOptions?.font?.measureText(topYLabel).width ?? 0;
   // Determine our x-output range based on yAxis/label options
   const oRange: [number, number] = (() => {
     const yTickCount =
```

On a side note, I don't believe it fully fixes https://github.com/FormidableLabs/victory-native-xl/issues/274, but it does seem to reduce the issue.

**Comment by zibs** [comment]
Thanks @owattenmaker -- I think this fix will require #259 to land first, as the existing Skia versions don't have `measureText` yet unfortunately! But if you're already on a Skia version that fixes this, then great!

If you want to make this a PR I can help land it afterwards.

**Comment by owattenmaker** [comment]
@zibs 

I can create a pr with some of my changes. As I've been playing around with it I've noticed some buggy behavior with the overall padding and spacing of the axis being created, so I can make a PR that addresses both this and #274. I also have a new feature PR which I'd like to submit handling the overlapping of labels if you're giving the tick values. 

Should I include all 3 changes in one PR or split into multiple (1 combo bug fix + 1 feature pr)?

**Comment by zibs** [comment]
Hey @owattenmaker feel free to make multiple PRs as it'll be easier to land them that way. You might want to branch off #259 as that contains the upgrade path forward for Skia 1.0+ (which you'll need for `measureText`) that should be landing soon.

Thanks a lot!

**Comment by owattenmaker** [comment]
I saw you guys just released v41. I will make the pr's off of main now. Have time this week to get these out, so hopefully can get them up in the next few days
