### ISSUE TITLE
different colors for each bar directly from the data

### ISSUE THREAD

**Issue by MatteoBrescianini** [FormidableLabs/victory-native-xl#296]
### Question

Hi everyone!! I'm working with Victory Native XL, with BarCharts and I'm trying to get the color of each bar directly from the data format...
such as in pie charts...
but it doesn't seem possible... has anyone already tried? 
basically my data is structured like this: {value:number, label:string, color:string}[], 
for each label a bar is created with the relative value... the problem is that the colors are all the same... and I can't access the color property or the current label of each bar... suggestions?

it will be fine if it's possible to have something like this:

   {({ points, chartBounds }) => (
                    <Bar
                        barWidth={30}
                        chartBounds={chartBounds}
                        points={points.value}
                        color={points.color} <----- 
                        animate={{ type: "timing" }}
                        roundedCorners={{
                            topLeft: roundedCorner,
                            topRight: roundedCorner,
                        }}
                    >
                    </Bar>
                )}

thanks for all answers!

**Comment by krisbot01** [comment]
This should be achievable with a custom bar component, [see this example from the documentation](https://commerce.nearform.com/open-source/victory-native/docs/cartesian/bar/use-bar-path).

**Comment by zibs** [comment]
Closing for #239 tracking
