### ISSUE TITLE
RN expo victory-native: TypeError: Cannot read property 'material' of undefined (a VictoryTheme)

### ISSUE THREAD

**Issue by Brise322** [FormidableLabs/victory-native-xl#297]
Environment and Dependencies:

•   Mac
•   “expo”: “51.0.12”
•   “react”: “18.2.0”
•   "react-native": "0.74.2"
•   “react-native-reanimated”: “~3.10.1”
•   “react-native-svg”: “^15.3.0”
•   “victory-native”: “^41.0.0”
After updating my environment, my charts suddenly stopped working. The error I get is: 

`ERROR TypeError: Cannot read property 'material' of undefined`

In fact, I found that none of the victory-native components are loading anymore. I tried logging VictoryTheme, but it also seems to be undefined.

Here are my import statements and the relevant code:

```
import { VictoryTheme } from 'victory-native';
import { VictoryChart, VictoryLine, VictoryZoomContainer, VictoryLabel, VictoryAxis, VictoryArea } from 'victory-native';
```

```
<VictoryChart
theme={VictoryTheme.material}
width={screenWidth}
height={220}
scale={{ x: "time" }}
padding={{ left: 20, top: 20, right: 80, bottom: 40 }}
containerComponent={  <VictoryZoomContainer responsive={false} />}
```

Can anyone help me resolve this issue?

**Comment by fant0mex** [comment]
Hi @Brise322 could I just confirm your react native version as well

**Comment by zibs** [comment]
If you're coming from the old Victory package then it is not always a simple migration to the new updates, and quite a few charts aren't quite complete yet, so you may want to check if it's possible for you to migrate yet or not!

**Comment by Brise322** [comment]
> Hi @Brise322 could I just confirm your react native version as well

Hi fant0mex,
My React Native version is 0.74.2. I created a small test Expo project and the error still exists. Someone replied after you, and I used version 37.0.2, which solved the problem. It was indeed an environment issue. Anyway thanks for your response

**Comment by Brise322** [comment]
> If you're coming from the old Victory package then it is not always a simple migration to the new updates, and quite a few charts aren't quite complete yet, so you may want to check if it's possible for you to migrate yet or not!
> 
> The latest victory-native you could be on for the legacy version is [37.0.2](https://github.com/FormidableLabs/victory/releases/tag/v37.0.2)

Hi zibs,

Thanks for your response. I used version 37.0.2, and the issue is resolved! It was indeed an environment configuration problem.
