### ISSUE TITLE
Set bottom padding on BarChart generates a visual error

### ISSUE THREAD

**Issue by TomCorvus** [FormidableLabs/victory-native-xl#300]
### Prerequisites

- [x] I have searched the open [issues](https://www.github.com/FormidableLabs/victory-native-xl/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/victory-native-xl/docs) before asking a question
- [x] I am using the latest version of victory-native-xl

### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`)
41.0.1

**What version of React and React Native are you using?**
0.74.1

**What version of Reanimated and React Native Skia are you using?**
1.2.3

**Are you using Expo or React Native CLI?**
No

**What platform are you on?** (e.g., iOS, Android)
iOS and Android

### Describe the Problem
On a BarChart, if I set bottom value in `domainPadding` prop, bars don't begin on 0.

**Expected behavior:** Can set bottom padding without this interfering on bars.

**Actual behavior:** Bottom padding generates an error on bars begin

### Additional Information

Just set `domainPadding={{ left: 50, right: 50, bottom: 30 }}`on BarGroup example.

<img width="533" alt="Capture d’écran 2024-06-17 à 16 38 31" src="https://github.com/FormidableLabs/victory-native-xl/assets/3451011/8225bcf9-f886-4705-bf42-1b55c95b3e52">

![Simulator Screenshot - iPhone 15 Pro Max - 2024-06-17 at 16 42 58](https://github.com/FormidableLabs/victory-native-xl/assets/3451011/ba469992-66b3-49c2-a566-be1475a67e0d)

**Comment by zibs** [comment]
Hey @TomCorvus is this what you would think it should look like?
<img width="388" alt="Screenshot 2024-06-18 at 3 00 28 PM" src="https://github.com/FormidableLabs/victory-native-xl/assets/1131641/1b167b7c-a0b9-49a1-b643-9b957a26156c">

**Comment by TomCorvus** [comment]
Hi @zibs, for me, yes.
`padding` prop seems to add padding around the chart and `domainPadding` inside the chart.
But bottom padding is the only property that interferes on bars size.
