### ISSUE TITLE
Empty charts with Expo; 'Points' result in empty object

### ISSUE THREAD

**Issue by JoelNgiamKeeYong** [FormidableLabs/victory-native-xl#312]
### Prerequisites

✅ I have searched the open [issues](https://www.github.com/FormidableLabs/victory-native-xl/issues) to make sure I'm not opening a duplicate issue
✅ I have read through the [docs](https://www.formidable.com/open-source/victory-native-xl/docs) before asking a question
✅ I am using the latest version of victory-native-xl

### Describe Your Environment

**What version of victory-native-xl are you using?** 
- v41.0.1, latest as of current date (i.e. 7 July 2024)

**What version of React and React Native are you using?** 
- "react": "^18.2.0";
- "react-native": "0.74.3"
- Both of which are controlled by the Expo SDK using "expo install"

**What version of Reanimated and React Native Skia are you using?**  
- "react-native-reanimated": "~3.10.1"
- "@shopify/react-native-skia": "1.2.3"

**Are you using Expo or React Native CLI?**
- "expo": "~51.0.17"

**What platform are you on?** (e.g., iOS, Android)
- iOS

### Describe the Problem

`
<CartesianChart data={graphData} xKey={"x"} yKeys={["y"]}>
{({ points, chartBounds }) => {
                    //👇 pass a PointsArray to the Line component, y0, as well as options.
                    console.log('Points:', points);
                    console.log('Chart bounds:', chartBounds);
                    return (
                        <Area
                            points={points.y}
                            y0={chartBounds.bottom}
                            color="red"
                            animate={{ type: "timing", duration: 300 }}
                        />
                    );
                }}
</CartesianChart>
`

- I used the starting example in the docs but was not able to display any charts at all even with other components besides the Area component.
- I suspect it has something to do with the 'points' child as it displays an empty object when I console log it in the example above, even though the data is populated when checking it in the console.
- This issue is similar to https://github.com/FormidableLabs/victory-native-xl/issues/172, but the solution there does not work for me.
- I also  used "npx expo-doctor@latest" to check if there are any issues with my dependencies - none found.

**Expected behavior:** Chart should appear

**Actual behavior:** No chart appears

### Additional Information

I have been using the legacy code and am porting over to the XL version. I currently reverted to the old legacy code and it works fine for those components. Will try to port over again once this issue has been solved.

**Comment by jamesagwa** [comment]
+1 I have got same issue. No chart appears and the points object is empty.

**Comment by zibs** [comment]
Can someone please post a reproducible example, and then I can take a look!

**Comment by jamesagwa** [comment]
@zibs see below. Using exact same packages and versions as stated above by @JoelNgiamKeeYong:

```typescript
import React from 'react'
import { StyleSheet, View } from 'react-native'
import { Bar, CartesianChart } from 'victory-native'
import { Text } from '@ui-kitten/components'

export function Chart({ data }: { data: { day: string; spent: number }[] }) {
  const mainData = [
    { day: 'Mon', spent: 450 },
    { day: 'Tue', spent: 120 },
    { day: 'Wed', spent: 50 },
    { day: 'Thu', spent: 350 },
    { day: 'Fri', spent: 100 },
    { day: 'Sat', spent: 150 },
    { day: 'Sun', spent: 200 },
  ]

  return (
    <View style={styles.container}>
      <Text category="c1">This week</Text>
      <CartesianChart
        data={mainData}
        xKey="day"
        yKeys={['spent']}
        domainPadding={{ left: 50, right: 50, top: 30 }}
        axisOptions={{
          formatXLabel(value) {
            return value
          },
        }}
      >
        {({ points, chartBounds }) => {
          console.log({ points })

          return (
            <Bar
              chartBounds={chartBounds}
              points={points.spent}
              color="red"
              roundedCorners={{ topLeft: 10, topRight: 10 }}
              barWidth={50}
              barCount={5}
            />
          )
        }}
      </CartesianChart>
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 300,
  },
  keyView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
})
```

logging `points` returns `{"points": {}}`

**Comment by zibs** [comment]
Thank you for the example @jamesagwa!

I can see here that the issue with the styling applied by the `View` container wrapping the chart. It seems like the `alignItems/justifyContent` props throw it all out of shape. If you remove those, you should see your chart. Sometimes when I'm having troubles with the chart/canvas, I set a specific height/width and mess around with flex to see if I'm getting it right or if there is indeed an issue. 

One aspect of the confusion here is that `points` is not truly an empty object. It's actually a `Proxy` and maybe we need to make that more clear in the docs somewhere. You can successfully log its values by using the `yKeys` of your data. So, if you logged `points.spent`, you will see the transformed data.

So my suggestions here is to review the styles applied to the chart/chart container, and log the actual `points[yKey]`, as `points` will always be an "empty" object.

In the meantime, I'll try to update the docs with the learnings here.
