### ISSUE TITLE
How to change the color of the bars?

### ISSUE THREAD

**Issue by andres-dos-santos** [FormidableLabs/victory-native-xl#313]
### Question

Hi guys, I just want to know a way to change the color of the bars, I have an array of colors and in version 36 I was using it like this:

```
const DATA = useMemo(() => {
  return data[PERIOD.PRODUCT[period!]].map((item, index) => ({
     ...item,
     id: item.productId,
     position: `${item.position}°`,
     color: COLORS[index],
   }))
}, [])
```

...and with this new version I believed that I would have an index to work with in the bar return function, something like this:

```
<CartesianChart
  data={DATA_BY_PERIOD}
  xKey="posicao"
  domainPadding={{ left: 20 }}
  domain={{ x: [0, 15] }}
  yKeys={['quantidadeTotal', 'valorTotal']}>
  {({ points, chartBounds, index }) => (
    <Bar
      points={points[VARIANT[variant!]]}
      chartBounds={chartBounds}
      color={COLORS[index]}
      roundedCorners={{ topLeft: 1, topRight: 1 }}
    />
  )}
</CartesianChart>
```

...but there isn't, what can I do in this situation?

**Comment by zibs** [comment]
Hey there -- feel free to take a look at: https://commerce.nearform.com/open-source/victory-native/docs/cartesian/guides/custom-bars and the example app inside this repo for examples on how to do that!

There is quite a big difference between the old victory-native and this new one, so it's not a 1:1 migration!
