### ISSUE TITLE
Dotted Axis ?

### ISSUE THREAD

**Issue by martinezguillaume** [FormidableLabs/victory-native-xl#321]
### Question

Hi ! I would like to do a chart a bit like this
<img width="448" alt="image" src="https://github.com/user-attachments/assets/f10d7466-7d63-4f85-8f10-04346c1f112e">
But it don't find any option to make this dotted axis, do I need to customize it from the scratch and not use the `grid` props ?
Thanks for any help / recommandations !

**Comment by jjojo** [comment]
I haven't found an intuitive way for this either unfortunately. Here are two workarounds though:

Make gridlines cover each other. This only seems to work for dotted y-lines though.
```JavaScript
axisOptions={{
            tickCount: 10,
            lineColor: {
              grid: {
                x: "black",
                y: "white",
              },
              frame: "transparent",
            },
            lineWidth: {
              grid: {
                x: 2,
                y: 5,
              },
              frame: 2,
            },
          }}
```

The other way is to use datapoints, with the <Line /> component, this feels like an anti-pattern but works.
```
 <Line
      points={points}
      color={"black"}
      strokeWidth={3}
    >
      <DashPathEffect intervals={[4, 4]} />
    </Line>
```

**Comment by samuthekid** [comment]
Would love to see this implemented! In the mean time, I'll create a bunch of <Lines> dotted 😅

**Comment by zibs** [comment]
Releasing now as `41.6.0`
