### ISSUE TITLE
Is there a way to add labels to the unique Pie.Slice's

### ISSUE THREAD

**Issue by mandelmann** [FormidableLabs/victory-native-xl#322]
I am currently working on a piechart with victory-native v41.0.2.
Is tere a way to add the labels inside the Pie.Slice or do I have to downgrade and use VictoryPie for my usecase?
It would look something like this:
![grafik](https://github.com/user-attachments/assets/3f4ba777-261c-429d-9e63-579b08c3d960)

**Comment by DevNomadAbhi** [comment]
I do have the same query , any workaround for this or should I downgrade the library?

**Comment by zibs** [comment]
There isn't an api for this currently no, so you would have to downgrade for now. It's on the roadmap to add this functionality.
