### ISSUE TITLE
Is there a way to select a particular Bar in the Bar chart using user Interactions, and change the color of that particular bar as and when its selected?

### ISSUE THREAD

**Issue by Gopi-Vuta** [FormidableLabs/victory-native-xl#326]
### Question

I would like to know how can I achieve the following requirement, 
Where I need to highlight the bar in the Bar graph that the user clicks/touches and make the color of it changed (to highlight it) and display the value of that Bar
<img width="805" alt="Screenshot 2024-08-05 at 9 53 45 PM" src="https://github.com/user-attachments/assets/be1cecd8-da4a-4a51-b320-4e94c13453ae">

### Background Info/Attempts

I have tried the below logic, But it changes the whole graph color, as it doesnt know which bar to be highlighted I guess

`const {state, isActive} = useChartPressState({
    x: 'Tue 09',
    y: {y: 2},
  });
  const barColor = isActive ? '#8894FF' : '#E9ECF1';`  

----

`<Bar
                  key={i}
                  points={points.y}
                  chartBounds={chartBounds}
                  color={barColor}
                  barWidth={20}
                  roundedCorners={{
                    topLeft: 20,
                    topRight: 20,
                    bottomLeft: 20,
                    bottomRight: 20,
                  }}
                />
                <MyAnimatedLine points={points.y} />
                {isActive ? `(<ToolTip` x={state.x.position} y={state.y.y.position} />) : null}`

**Comment by Valli-** [comment]
@Gopi-Vuta any ideas? I'm trying to achieve this as well..

**Comment by Gopi-Vuta** [comment]
Hey @Valli- Nope not from this library, I was not able to achieve this scenario using the library and since its a spike that we are doing and in the initial staging of adopting the library we had to move to a different library all together.

**Comment by zibs** [comment]
This should be possible: https://commerce.nearform.com/open-source/victory-native/docs/cartesian/guides/custom-bars, as well as you can run the example app in this repo, and look at this example: https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/bar-charts-custom-bars.tsx

**Comment by cr0nil** [comment]
In the case where the label 'X' is repeated on the axis, we are unable to determine which bar we have selected. For example, if we have 'Friday' twice, based on the state (useChartPressState), we cannot determine which one is being referred to. In my opinion, we should be able to click on the Bar or the state (useChartPressState) should return the index of the bar.

**Comment by keithluchtel** [comment]
> In the case where the label 'X' is repeated on the axis, we are unable to determine which bar we have selected. For example, if we have 'Friday' twice, based on the state (useChartPressState), we cannot determine which one is being referred to. In my opinion, we should be able to click on the Bar or the state (useChartPressState) should return the index of the bar.

Can you share a code snippet of how your `data` is formatted?

**Comment by cr0nil** [comment]
If you have this example (https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/bar-charts-custom-bars.tsx) and you want to get the selected bar (activeXItem) on click for such a data set, you're not able to do it correctly.
```
[
  {"weekday": "Monday", "value": 0.89},
  {"weekday": "Tuesday", "value": 0.78},
  {"weekday": "Wednesday", "value": 0.48},
  {"weekday": "Thursday", "value": 0.40},
  {"weekday": "Friday", "value": 0.35},
  {"weekday": "Saturday", "value": 0.31},
  {"weekday": "Sunday", "value": 0.34},
  {"weekday": "Monday", "value": 0.85},
  {"weekday": "Tuesday", "value": 0.75},
  {"weekday": "Wednesday", "value": 0.45},
  {"weekday": "Thursday", "value": 0.38},
  {"weekday": "Friday", "value": 0.33},
  {"weekday": "Saturday", "value": 0.30},
  {"weekday": "Sunday", "value": 0.36}
]
```

**Comment by keithluchtel** [comment]
Fixed in version `41.8.0`

**Comment by Batoul-Ammar** [comment]
Is there a way to select a bar in a bar group chart? the `matchedIndex` will return the matched group and not one specific bar index in that group.

**Comment by keithluchtel** [comment]
> Is there a way to select a bar in a bar group chart? the `matchedIndex` will return the matched group and not one specific bar index in that group.

I don't think this is currently possible. If you like, create a new issue and we can track it there as a potential enhancement
