### ISSUE TITLE
How to color a Line inside CartesianChart based on point value?

### ISSUE THREAD

**Issue by Dan-Berezin** [FormidableLabs/victory-native-xl#341]
### Question

I'm plotting a very simple line graph. The data are pairs of "timestap", which is a float number coming from a scaled Datetime, and a value. All that is working as expected. I would like to color the line depending on its height, for example, for every point below 50 to be plotted in green, between 50 and 100 yellow and above 100 in red. That's the general idea. I'm using victory-native 40.0.0 on an Expo 50 project.

### Background Info/Attempts

```

return (
    <>
      <LineChartHeader
        localDateTime={localDateTime}
        currentValue={maxValue}
        currentLabel={type}
      />
      <View style={styles.chartContainer}>
        {isFetching && <Spinner />}
        <CartesianChart
          data={scaledData}
          xKey="timestamp"
          domain={{ x: [0, xMaxValue], y: [0, yMaxDomain] }}
          yKeys={['value']}
          axisOptions={{
            formatXLabel: (value) =>
              dayStart.set({ hour: value }).toLocaleString(DateTime.TIME_24_SIMPLE),
            font,
            lineColor: {
              grid: {
                x: theme.colors.transparent,
                y: theme.colors.transparent,
              },
              frame: theme.colors.transparent,
            },
            lineWidth: 1,
            labelColor: theme.colors.colorBasic6,
            labelOffset: 10,
          }}
          domainPadding={{ left: 10, right: 10, top: 10, bottom: 0 }}
        >
          {({ points }) => (
            <Line
              points={points.value}
              color={theme.colors.white}
              strokeWidth={1}
              connectMissingData
            />
          )}
        </CartesianChart>
      </View>
    </>
  )
```
this is how the plot looks like:
![plotexamplewhite](https://github.com/user-attachments/assets/0cf3e3a4-8315-45eb-b78e-ea06e04ec707)

and this is how I need it to look like:
![plotexample](https://github.com/user-attachments/assets/4896cf36-3cc6-4e6a-8ea9-9cb3a71c46aa)

**Comment by crcarlo** [comment]
A possible solution to your problem would be to write a custom shader which gives the line different colors based on the y scale.

I tried out making a shader like this here https://github.com/crcarlo/victory-native-xl/blob/horizontal-bands-shader/example/app/horizontal-bands-line.tsx#L29

<img width="905" alt="Screenshot 2024-08-28 at 13 47 06" src="https://github.com/user-attachments/assets/f0d60ae1-b71e-40b6-b446-23d80c281480">

You can use it by providing thresholds for the colors like seen here https://github.com/crcarlo/victory-native-xl/blob/horizontal-bands-shader/example/app/horizontal-bands-line.tsx#L110

The thresholds are basically

```jsx
[
  [yValue1, [r1, g1, b1],
  [yValue2, [r2, g2, b2],
  //...
]
```

so you have the color `[r1, g1, b1]` for values above `yValue1` and so on.

**Comment by zibs** [comment]
Gonna close this as I think we've covered some great ground here and laid out a possible solution for anyone else!
