### ISSUE TITLE
How can I do two/three or four colors, more than one on a single Bar, not LinearGradient

### ISSUE THREAD

**Issue by GezimVeliu** [FormidableLabs/victory-native-xl#342]
The example on the website is for web, but I am confused about how we can do it in Victory Native for React Native. We have so many options to customize this, but which is the best approach to keep it simple? Please take a look at the image link:

![image](https://github.com/user-attachments/assets/3479302f-d064-4e6c-832b-2e033526a481)

**Comment by zibs** [comment]
Are you looking for #315? It's in review for now, but if that's what you're interested in, please check out the branch and let me know how it goes for you!
