### ISSUE TITLE
Inaccurate gradient in example

### ISSUE THREAD

**Issue by crcarlo** [FormidableLabs/victory-native-xl#344]
### Describe Your Environment

Noticed a problem while taking a look at the examples in this repository.

### Describe the Problem

It's barely noticeable, but there is a mistake in the “Ordinal Data” example. In this example the line color gradient was supposed to go from top to bottom but is actually going diagonally.

It's hard to notice because of the line being thin, but towards the end of the chart you can see a difference between the interpolated color of the dot when selecting a day (correct) and the underlying line because of the gradient being slightly tilt.

Furthermore the gradient height does not consider the top padding (the problem is evident when vertically squeezing the chart).

**Comment by simoneb** [comment]
Since this is a UI glitch, can you please include a screenshot of what it looks like before/after your change?

**Comment by crcarlo** [comment]
## Incorrect gradient direction

Before:
<img width="813" alt="0-before" src="https://github.com/user-attachments/assets/c079dd5b-6e47-4e8b-8013-c2a05e172705">
> You can see that the color on monday and friday is almost the same even though they have very different values, the color on sunday is colder than wednesday even if the value is higher

After:
<img width="813" alt="0-after" src="https://github.com/user-attachments/assets/3d8c682d-48a6-4229-be4e-8335e493e108">
> The problem is solved

## Case of very short vertical axis
Before:
<img width="1512" alt="1-before" src="https://github.com/user-attachments/assets/83eb7789-fe0d-4983-ba02-d8c495858b28">
> The problem is evident here

After:
<img width="1512" alt="1-after" src="https://github.com/user-attachments/assets/7af34168-bb88-4d49-95ba-836af37de474">
> The problem is solved

**Comment by biapar** [comment]
How to add the gradient by Y value like that?

**Comment by simoneb** [comment]
> How to add the gradient by Y value like that?

See the line that's changed in the linked PR: #345. It's from one of the examples in the repo.

**Comment by biapar** [comment]
I follow this example: https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/horizontal-bands-line.tsx
Is there a more simple method?

**Comment by keithluchtel** [comment]
> I follow this example: https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/horizontal-bands-line.tsx Is there a more simple method?

You can also look at the Ordinal Data example: https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/ordinal-data.tsx

The gradient is handled by Skia, you can also reference their docs: https://shopify.github.io/react-native-skia/docs/shaders/gradients/

**Comment by biapar** [comment]
Thanks, but that is an example to add only the gradient but not by value ( think to a chart with temperatures ).

**Comment by crcarlo** [comment]
@biapar if I understand correctly you are looking for a way of having a gradient which varies the color based on the y value rather than having it depending on the height of the chart.

The example you were looking at https://github.com/FormidableLabs/victory-native-xl/blob/main/example/app/horizontal-bands-line.tsx was exactly what you were looking for. That's the only straight forward way I found for doing it, but I understand it's simpler since it only colors the chart by bands of uniform color. One way to adapt it to your use case could be to interpolate the colors in the Skia shader, but I understand it's not a very straight forward solution.
