### ISSUE TITLE
Unable to modify Frame color or width for Cartesian Chart

### ISSUE THREAD

**Issue by ramspeedy** [FormidableLabs/victory-native-xl#377]
### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`)
victory-native@41.4.0

**What version of React and React Native are you using?**
react@18.2.0 
react-native@0.74.1

**What version of Reanimated and React Native Skia are you using?**
react-native-reanimated@3.10.1
@shopify/react-native-skia@1.3.3

**Are you using Expo or React Native CLI?**
Expo

**What platform are you on?** (e.g., iOS, Android)
iOS

### Describe the Problem
@zibs Firstly thanks for making the change for multiple y Axes! I think between 41.3.0 and 41.4.0 however, I've lost the ability to adjust the Frame color (either through deprecated axisOptions or using the new frame prop.

**Expected behavior:** Change frame width and color (or make invisible)

**Actual behavior:** Not able to change any aspect of frame color or width on CartesianChart

### Additional Information

Seems like this was introduced in 41.4.0

**Comment by zibs** [comment]
Oh, thanks it's possible I've missed that! I'll take a look and add it back if so.
