### ISSUE TITLE
Customizing label position and rotation on StackedBar 

### ISSUE THREAD

**Issue by Dan-Berezin** [FormidableLabs/victory-native-xl#388]
Hi,
I'm using victory-native 41.6.0 and StackedBars component. My goal is to build an horizonal plot where every bar is the same length but the proportions amongst the two colors from each bars shows the progress. This is how it should look like:
<img width="382" alt="Captura de pantalla 2024-10-04 a la(s) 6 47 58 p m" src="https://github.com/user-attachments/assets/0e549356-4ffe-4458-8ca7-164b1ef982a1">

I'm currently having issues with the position of the labels. The rendering of my code looks like this:

<img width="294" alt="Captura de pantalla 2024-10-04 a la(s) 6 48 46 p m" src="https://github.com/user-attachments/assets/c9edc2f2-ddc1-43ac-a6aa-268b7fce826e">

is there a way to either rotate and position the labels or to render some Text component as children for each StackedBar that I can customize fully? Or even to overlay some text on the graph so I can achieve this result?
Thanks

**Comment by zibs** [comment]
Hey @Dan-Berezin, it almost seems to me that it would be easier to just use Skia itself here without the library.

```tsx
// map through each data point:
<View>
 <View style={{flexDirection: 'row', justifyContent: 'space-between'}}>
  <Text>label</Text>
  <Text>data</Text>
  <Canvas>
     // figure out how to draw a simple straight rectangle line the width you need etc.
     <Path/Line color />
     <Path/Line gray color />
  </Canvas>

 </View>
</View>
```
