### ISSUE TITLE
The size of the Pie should be configurable, i.e. less than the canvas size to display label outside of the pie

### ISSUE THREAD

**Issue by hexadecy** [FormidableLabs/victory-native-xl#390]
### Description

The top of the label is cut when outside the canvas. I'm sure it's the same thing for the bottom.
This can happen if Pie.Label radiusOffset is equal to or greater than one.

### Versions
"victory-native": "41.6.0"

### Example
```jsx
import React from 'react';
import { StyleSheet, Platform } from 'react-native';
import { Pie, PolarChart } from 'victory-native';
import { matchFont } from '@shopify/react-native-skia';

const MyExamplePie = () => {
  const fontFamily = Platform.select({ ios: 'Noto Sans', default: 'serif' });
  const fontStyle = {
    fontFamily,
    fontSize: 14,
    fontWeight: 'bold',
  };
  const font = matchFont(fontStyle);
  const data = [{c: '#f07048', x: 'Dry', y: 70}, {c: '#48cd83', x: 'Good', y: 22}, {c: '#4782cd', x: 'Wet', y: 8}]
  
  return (
    <PolarChart containerStyle={styles.polarChart} data={data} labelKey="x" valueKey="y" colorKey="c">
      <Pie.Chart containerStyle={styles.pieChart} startAngle={270} innerRadius="50%">
        {() => {
          return (
            <>
              <Pie.Slice />
              {data.length > 1 && (
                <Pie.SliceAngularInset
                  angularInset={{
                    angularStrokeWidth: 4,
                    angularStrokeColor: '#f6f6f6',
                  }}
                />
              )}
              <Pie.Label radiusOffset={0.96} font={font} color="black" />
            </>
          );
        }}
      </Pie.Chart>
    </PolarChart>
  );
}

const styles = StyleSheet.create({
  polarChart: {
    height: 175,
  },
  pieChart: {
    height: 150, // do nothing
  }
}
```

![Pie with labels](https://github.com/user-attachments/assets/0d2f3297-3507-4b6b-9eba-c1f0f3ec2002)

### Proposal

Add containerStyle to Pie.Chart to change the height or width of the pie

**Comment by zibs** [comment]
Hey @hexadecy -- I'm curious if through a combination of https://commerce.nearform.com/open-source/victory-native/docs/polar/polar-chart#containerstyle and https://commerce.nearform.com/open-source/victory-native/docs/polar/polar-chart#containerstyle you would be able to come to a solution to your issue here. You could also experiment with adjusting font size etc.

Let me know!

**Comment by hexadecy** [comment]
Yes, I tried that and we can only change the polar-chart containerStyle.
I don't want to change the font size because I want the label far from the pie.
I'm migrating from victory-native 37.

The pie-chart `canvasSize` came from `usePolarChartContext`.
I've checked to see if I can do a workaround, but I don't see any.

https://github.com/FormidableLabs/victory-native-xl/blob/ae898f7c91e47d1e63a61bf9e58f41b923809c22/lib/src/pie/PieChart.tsx#L24-L42

**Comment by zibs** [comment]
@hexadecy Ooooh I see more what you mean now, and look we even have a comment about it! Okay, I'll look into it a bit more.

**Comment by zibs** [comment]
Would https://github.com/FormidableLabs/victory-native-xl/pull/392 help you @hexadecy ?

**Comment by hexadecy** [comment]
Yes, I think it's good. Tanks.
