### ISSUE TITLE
Modify the frame setting for a particular side of the axis.

### ISSUE THREAD

**Issue by rajdivergenceneuro** [FormidableLabs/victory-native-xl#394]
### Description
Hello folks,

I need information on new victory-chart.

I had old victory-native chart version and moving to new victory-native-xl. I am facing UI related issue where I am not able to remove only top and right axis of frame which was configurable in old victory-native library chart.

![Screenshot_20241009_182021](https://github.com/user-attachments/assets/da54feb0-9ee2-459a-b19f-c66e71ba2cc2)

Your suggestion will be greatly appreciated.

**Comment by keithluchtel** [comment]
I don't believe removing only certain sides from the frames is available currently. I think a workaround would be hiding the from entirely from the chart, and then custom drawing your frame with the `renderOutside` option.

**Comment by rajdivergenceneuro** [comment]
> I don't believe removing only certain sides from the frames is available currently. I think a workaround would be hiding the from entirely from the chart, and then custom drawing your frame with the `renderOutside` option.

Is there any possibility to add this feature in upcoming update where we can hide any axis from frame by props?

**Comment by keithluchtel** [comment]
> Is there any possibility to add this feature in upcoming update where we can hide any axis from frame by props?

This seems like something that could be added, but don't have a timeline on when it'd be available.

**Comment by rajdivergenceneuro** [comment]
Thank you for giving feature enhancement in very short time.

**Comment by keithluchtel** [comment]
@rajdivergenceneuro This has been released in version `41.7.0`

Unrelated, if you're working on anything cool using victory native and would like to share, head over to our showcase thread: https://github.com/FormidableLabs/victory-native-xl/discussions/398
