### ISSUE TITLE
StackBar is overlaying when the data of graph are increasing 

### ISSUE THREAD

**Issue by rajdivergenceneuro** [FormidableLabs/victory-native-xl#401]
https://github.com/user-attachments/assets/33b6aeef-6ce7-4586-906f-68050d88787b

### Description
Hello folks,

- When I increase the number of data in the Stackbar, it is not adjusting padding after some point as like simple bar graph. it is overlaying above each other.  is it possible to do auto adjustment in Stackbar?

### Proposal
Your suggestion will be greatly appreciated.

**Comment by rajdivergenceneuro** [comment]
Thank you team for resolving issue in short time

**Comment by keithluchtel** [comment]
@rajdivergenceneuro this has been released in version `41.7.0`
