### ISSUE TITLE
Gridline positions

### ISSUE THREAD

**Issue by cr0nil** [FormidableLabs/victory-native-xl#408]
Is it possible to get the y position of the Yaxis grid line and the x position for the Xaxis grid line, e.g. for position 0 where the bars start from? This would make it easier to apply skia elements based on the grid line position

**Comment by keithluchtel** [comment]
Let me look into this. I don't think there's a way to easily do it currently, but hopefully a small change can expose all the information needed. My initial thought it exposing additional params in the `renderOutside` function args

**Comment by keithluchtel** [comment]
@cr0nil give this a look (https://github.com/FormidableLabs/victory-native-xl/pull/409) to see if this would fit your needs
