### ISSUE TITLE
Support for activeOffset and failOffset in CartesianChart

### ISSUE THREAD

**Issue by hirbod** [FormidableLabs/victory-native-xl#410]
### Description

The Cartesian chart gesture detector should support passing values for activeOffset and failOffset (both X and Y axes).

Currently, in the CartesianChart, only longPressDelay is supported.

While this setting helps to prevent touch hijacking in ScrollViews and still allows fullScreenGestureEnabled by react-native-screens to work, it remains quite limiting. In our case, setting the delay to 0 enables immediate touch updates without requiring a long press, which is what we are aiming for, but it now prevents vertical scrolling.

Losing the fullscreen swipe on the chart is acceptable, as swiping from the edge to pop, along with the back arrow, still functions correctly. But. We still want to scroll vertically without interfering.

### Proposal

Enable the passing of activeOffsetX, activeOffsetY, failOffsetX, and failOffsetY.

Why? This change would allow us to limit touch activation on the X axis while retaining vertical scrolling without any touch delay. It provides greater control over touch activation, eliminating the need to patch the library.

### Links / References

https://docs.swmansion.com/react-native-gesture-handler/docs/gestures/pan-gesture#activeoffsetxvalue-number--number

**Comment by keithluchtel** [comment]
fixed in 41.12.0
