### ISSUE TITLE
Short press not working

### ISSUE THREAD

**Issue by cr0nil** [FormidableLabs/victory-native-xl#412]
press for a short tap does not work, only a longer press changes the state(chartPressState), verify the Gesture.Pan() method

**Comment by keithluchtel** [comment]
@cr0nil does setting `gestureLongPressDelay={0}` work?

**Comment by cr0nil** [comment]
for the value 0, it does not work at all, the CartesianChart component is wrapped by scrollview (horizontally), clicking for small values ​​of gestureLongPressDelay (e.g. 20 or 50) works better, but then it is more difficult to scroll through the entire width of the chart

**Comment by keithluchtel** [comment]
Ah, okay. We currently don't have a `Tap` gesture added to the charts. Let me think about how we want to add this.

**Comment by keithluchtel** [comment]
@cr0nil I've added this draft PR (#417) as a potential solution that'd allow you to define your own `Tap` gesture. Let me know your thoughts.

**Comment by cr0nil** [comment]
yes, looks good

**Comment by keithluchtel** [comment]
fixed in 41.12.0
