### ISSUE TITLE
ChartBounds not starting where I expect it

### ISSUE THREAD

**Issue by svenlombaert** [FormidableLabs/victory-native-xl#421]
### Prerequisites

- [x] I have searched the open [issues](https://www.github.com/FormidableLabs/victory-native-xl/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/victory-native-xl/docs) before asking a question
- [x] I am using the latest version of victory-native-xl

### Describe Your Environment

**What version of victory-native-xl are you using?** (can be found by running `npm list --depth 0 victory-native`)
41.9.0

**What version of React and React Native are you using?**
react-native 0.73.8, react 18.2

**What version of Reanimated and React Native Skia are you using?**
reanimated: 3.6.1, skia: 1.5.3

**Are you using Expo or React Native CLI?**
cli

**What platform are you on?** (e.g., iOS, Android)
iOS & Android

### Describe the Problem

**Expected behavior:** I would expect a simple chart without any axis to have chartBounds left: 0; bottom: height of chart

**Actual behavior:** When I set the parent view style to `width: Dimensions.get('window').width, height: 160` chartBounds are: ```{"bottom": 152, "left": 4, "right": 393, "top": 0}```

This is the code I'm using to draw the chart:
```typescript
<View
  style={{
    height: 160,
    width: Dimensions.get('window').width,
    borderColor: 'blue',
    borderWidth: 1,
  }}
>
  <CartesianChart
    data={points}
    xKey="x"
    yKeys={['y']}
    domain={{ y: domainY }}
  >
    {({ points, chartBounds, canvasSize }) => {
      console.log('chartBounds', chartBounds);
      console.log('canvasSize', canvasSize);
      return (
        <Area
          points={points.y}
          y0={chartBounds.bottom}
          color="red"
          curveType="monotoneX"
        />
      );
    }}
  </CartesianChart>
</View>
```

Is there any way to set the chartBounds?

### Additional Information

This is the new victory-native and the old one stacked. I wonder how I draw the area without the left and bottom blank space.

<img src="https://github.com/user-attachments/assets/4a9762a0-8cd4-49f2-a4eb-69a02e7b5185" width="50%" />

**Comment by keithluchtel** [comment]
The `labelOffset` of the axis gets defaulted to `4` if none is provided. See docs: https://commerce.nearform.com/open-source/victory-native/docs/cartesian/cartesian-chart#yaxis

If you manually define your `labelOffset` for particularly the `yAxis` in this example to `0`, it should give you the chart bounds you are expecting.

**Comment by svenlombaert** [comment]
> The `labelOffset` of the axis gets defaulted to `4` if none is provided. See docs: https://commerce.nearform.com/open-source/victory-native/docs/cartesian/cartesian-chart#yaxis
> 
> If you manually define your `labelOffset` for particularly the `yAxis` in this example to `0`, it should give you the chart bounds you are expecting.

Oh wow 🤦 thanks!

Because the docs said the yAxis and xAxis props were optional, I did not expect them to have any values by default 😅

**Comment by keithluchtel** [comment]
There's a handful of optional props that have some default values. I can understand the confusion and will be mindful of that going forward!
