### ISSUE TITLE
Is it possible to enable horizontal scrolling on the x-axis?

### ISSUE THREAD

**Issue by Jothebug** [FormidableLabs/victory-native-xl#424]
### Question

Hi everyone,

I have a question: is it possible to enable horizontal scrolling on the x-axis? In my case, I have a large array of data, and I want to display 3 items in the chart viewport at a time. If I want to see more, I would like to be able to scroll horizontally. You can refer to the GIF below for reference.

![Scrollable](https://github.com/user-attachments/assets/bce22add-859f-4d5c-b8dc-7b8ccd625f50)

I stuck with that issue for couple of weeks, so anyone has any ides, plz let me know. 
Thank you so much in advance.

**Comment by keithluchtel** [comment]
This is not currently possible. I have a PR up to support pan/zoom support. Once that's merged, I can look at expanding upon to it offer this functionality. No promises on timelines.

**Comment by tobiyas09** [comment]
You can wrap your chart in horizontal ScrollView and make the width of the chart `data.length*60`.
You can scroll horizontally but sadly you won't see y-axis

**Comment by keithluchtel** [comment]
I'm actively working on a solution for this now and should have something available soon.
