### ISSUE TITLE
Is it possible to display chart grid without data?

### ISSUE THREAD

**Issue by MKolisz** [FormidableLabs/victory-native-xl#428]
### Question

I have added scrolling to my chart, and there are cases where certain ranges contain no data, causing the chart to disappear. Is it possible to display the grid when there is no data available?

### Background Info/Attempts

I tried passing fake data to keep chart visible but it might be confusing for users

**Comment by zibs** [comment]
@MKolisz Can you send us an example repository to take a look at there. Curious as to what you mean!

**Comment by MKolisz** [comment]
Hi, I've just realised that I can solve this by setting CartesianChart y domain to a default value when there is no data to be displayed. Thanks for an answer and sorry for the confusion! This can be closed.
I ask and encourage you to take a look at lack of rotation for xLabels issue https://github.com/FormidableLabs/victory-native-xl/issues/275 :)
