### ISSUE TITLE
Dashed/dotted line

### ISSUE THREAD

**Issue by gknit** [FormidableLabs/victory-native-xl#429]
Hi all,

This is a naive question, but I don't find the respective info in the documentation: How can I change the line style to e.g. dashed or dotted?

Best and many thanks,
Gero

**Comment by keithluchtel** [comment]
You can change the style of the line by using a path effect as shown in the the Skia documentation: https://shopify.github.io/react-native-skia/docs/path-effects#example-1

If you want to change the axis lines, here's the documentation: https://commerce.nearform.com/open-source/victory-native/docs/cartesian/cartesian-chart#xaxis , there's a `linePathEffect` prop for the axis.

**Comment by keithluchtel** [comment]
Going to close. Feel free to reopen if the above suggestions doesn't solve your issue.

**Comment by gknit** [comment]
That was easy, thank you!

**Comment by joprice** [comment]
@idanlevi1 I noticed this wasn't working for me until I removed `animate={{type: 'timing', duration: 300}}` from the line's props. Are these two configurations incompatible?
