### ISSUE TITLE
How does Victory Chart calculate Y axis values

### ISSUE THREAD

**Issue by davram88** [FormidableLabs/victory-native-xl#442]
### Question

When rendering a user's account balance, 
I may have y axis values of [100, 125, 150, 200] that is autogenerated by the chart which is fine. 
Sometimes the chart autogenerates with decimal places  [100, 125.5, 150.5,  200] which is a problem. 

I want to normalize this so that if there are decimal places in one of the y axis values. Every label should be toFixed(2) (two decimals). 

So the above example would be [100.00, 125.50, 150.50,  200.00] 

How can I do that? If that can't be done within the API, is there a function somewhere in the codebase that calculates the y axis values that I can run before rendering the chart and having a flag for formatYLabel to render with decimal places or not.

Any help would be appreciated! 
Thanks

**Comment by keithluchtel** [comment]
does using the `formatYLabel` option for `yAxis` work for your scenario?

https://commerce.nearform.com/open-source/victory-native/docs/cartesian/cartesian-chart#yaxis
