### ISSUE TITLE
Got weird Y tick label even if I manually specify tick values

### ISSUE THREAD

**Issue by kuan0808** [FormidableLabs/victory-native-xl#449]
### Question
I’ve encountered an issue while using the `tickValues` option for customizing the Y-axis labels. According to the documentation, this feature allows users to specify custom Y-tick values. For example, I set the labels to `[10, 20, 30, 40]`. However, the rendered chart does not display these labels correctly. Instead, the Y-tick labels appear as strange, irregular values, often with several decimal places, which I didn’t specify.

It seems like the `tickValues` option is not functioning as expected. Could you please confirm if this is a bug or if there’s something I might have missed in the setup?

And I have another question: it seems like the Y-axis labels on the left and right sides can’t have different tick counts.

I’d appreciate any guidance or suggestions to resolve this issue. Thank you in advance!

### Background Info/Attempts

For example, I specify `[0, 10, 20, 30, 40, 50]` for tickValues for the right YAxis. But instead I got this result
![image](https://github.com/user-attachments/assets/52fc1d15-abba-44be-8571-77d34915c425)

**Comment by keithluchtel** [comment]
@kuan0808 what version of victory-native are you using? We just recently released an updated that adjusted some of the y-axis tick behavior.

**Comment by kuan0808** [comment]
> @kuan0808 what version of victory-native are you using? We just recently released an updated that adjusted some of the y-axis tick behavior.

This is what I specified in my package.json

```
"victory-native": "^41.9.0",
```

**Comment by keithluchtel** [comment]
> May I ask which version I should upgrade to in order to resolve this issue?

`41.12.3` and later should hopefully address the issue. Give that a try and let me know if still having issues.

**Comment by kuan0808** [comment]
I am currently on `victory-native@41.12.5`, and I can now confirm that the issue has been resolved. Thank you for your help🤩
