### ISSUE TITLE
Tickcount value doesn't change the actual tickcount

### ISSUE THREAD

**Issue by DaveMonGym** [FormidableLabs/victory-native-xl#450]
### Describe Your Environment

**What version of victory-native-xl are you using?** 
41.12.2

**What version of React and React Native are you using?**
React 18.3.1
React Native 0.76.3

**What version of Reanimated and React Native Skia are you using?**
Reanimated 3.16.1
React Native Skia 1.5.0

**Are you using Expo or React Native CLI?**
Expo

**What platform are you on?** (e.g., iOS, Android)
Android

### Describe the Problem

The tickcount prop within yAxis and xAxis does not take into account some numbers.
In this screenshot, I've set the tickcount to 4, but it still renders 6.
If I set it to 2, it works, but 3,4,5,7,8,9 does absolutly nothing
![Screenshot_20241212_144304_rnd-app](https://github.com/user-attachments/assets/b16541fd-8e3e-4cf3-b5b3-09905e75762c)

**Expected behavior:** 
Tickcount prop to render the expected input

**Actual behavior:** 
Tickcount does not render input

**Comment by zibs** [comment]
Hey @DaveMonGym You can see in the docs https://commerce.nearform.com/open-source/victory-native/docs/cartesian/cartesian-chart#xaxis that it says:

```Note: This is an approximation; the scale may return more or fewer values depending on the domain, padding, and axis labels.```
