### ISSUE TITLE
Set up Provenance

### ISSUE THREAD

**Issue by carloskelly13** [FormidableLabs/victory-native-xl#95]
Set up package provenance for stable v40 releases

https://github.blog/2023-04-19-introducing-npm-package-provenance/

**Comment by gksander** [comment]
Should hopefully be able to just follow e.g. [this PR](https://github.com/FormidableLabs/react-native-owl/pull/155) and add a few lines of config, and should be good to go 🪂

**Comment by gksander** [comment]
We gucci.

<img width="223" alt="image" src="https://github.com/FormidableLabs/victory-native-xl/assets/12721310/6f24d93c-2ba5-41ce-a6d3-b7c6fb0c7cd2">
